### ISSUE TITLE
Unable to build a project with net7 RC 1

### ISSUE THREAD

**Issue by florianwachs** [dotnet/maui#10234]
### Description

Upgraded to newest VS Preview with support for maui .net 7 RC 1, but I´m unable to build the project. The output complains that workloads for IOS and MacCatalyst are missing. I repaired both, .net 7 RC1 SDK and VS but it had no effect.

Output of dotnet workload list:
```
Installierte Workload-ID      Manifestversion                   Installationsquelle
-----------------------------------------------------------------------------------
maui-windows                  7.0.0-rc.1.6683/7.0.100-rc.1      VS 17.4.32916.344
maui-maccatalyst              7.0.0-rc.1.6683/7.0.100-rc.1      VS 17.4.32916.344
maccatalyst                   15.4.1006-rc.1/7.0.100-rc.1       VS 17.4.32916.344
maui-ios                      7.0.0-rc.1.6683/7.0.100-rc.1      VS 17.4.32916.344
ios                           15.4.1006-rc.1/7.0.100-rc.1       VS 17.4.32916.344
maui-android                  7.0.0-rc.1.6683/7.0.100-rc.1      VS 17.4.32916.344
android                       33.0.0-rc.1.151/7.0.100-rc.1      VS 17.4.32916.344
```

Output VS Error View
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net7.0-ios, net7.0-maccatalyst	MauiApp11	C:\src\stuff\MauiApp11\MauiApp11.csproj	1	
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net7.0-ios, net7.0-maccatalyst	MauiApp11	C:\src\stuff\MauiApp11\MauiApp11.csproj	1	
Error	NETSDK1147	To build this project, the following workloads must be installed: maccatalyst
To install these workloads, run the following command: dotnet workload restore	MauiApp11	C:\Program Files\dotnet\sdk\7.0.100-rc.1.22431.12\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets	38	
```

Output dotnet workload restore
```
PS C:\src\stuff\MauiApp11> dotnet workload restore
Installing workloads: ios maccatalyst

Downloading Microsoft.iOS.Sdk.Msi.x64 (15.4.1006-rc.1)
Workload installation failed. Rolling back installed packs...
Downloading microsoft.net.sdk.tvos.manifest-7.0.100-rc.1.msi.x64 (15.4.1006-rc.1)
Installation rollback failed: One or more errors occurred. (microsoft.net.sdk.tvos.manifest-7.0.100-rc.1.msi.x64::15.4.1006-rc.1 is not found in NuGet feeds https://api.nuget.org/v3/index.json;C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\;https://kreon.halvotec.local/Collection1/_packaging/HalvotecPackages/nuget/v3/index.json".)
Downloading microsoft.net.sdk.maccatalyst.manifest-7.0.100-rc.1.msi.x64 (15.4.1006-rc.1)
Installation rollback failed: One or more errors occurred. (microsoft.net.sdk.maccatalyst.manifest-7.0.100-rc.1.msi.x64::15.4.1006-rc.1 is not found in NuGet feeds https://api.nuget.org/v3/index.json;C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\;https://kreon.halvotec.local/Collection1/_packaging/HalvotecPackages/nuget/v3/index.json".)
Downloading microsoft.net.sdk.ios.manifest-7.0.100-rc.1.msi.x64 (15.4.1006-rc.1)
Installation rollback failed: One or more errors occurred. (microsoft.net.sdk.ios.manifest-7.0.100-rc.1.msi.x64::15.4.1006-rc.1 is not found in NuGet feeds https://api.nuget.org/v3/index.json;C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\;https://kreon.halvotec.local/Collection1/_packaging/HalvotecPackages/nuget/v3/index.json".)
Workload installation failed: One or more errors occurred. (microsoft.ios.sdk.msi.x64::15.4.1006-rc.1 is not found in NuGet feeds https://api.nuget.org/v3/index.json;C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\;https://kreon.halvotec.local/Collection1/_packaging/HalvotecPackages/nuget/v3/index.json".)PS C:\src\stuff\MauiApp11>
```

### Steps to Reproduce

1. Update to newest VS preview
2. Create a new maui project
3. Build
4. => Errors in Error View

### Link to public reproduction project repository

why? dotnet new maui

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

doesn´t matter

### Did you find any workaround?

no

**Comment by Conbag93** [comment]
+1 for this - I also have the same issue.

I also tried completely removing Visual Studio 2022 Preview and doing a fresh install.
Doing this resulted in losing all of the MAUI + Blazor Hybrid project templates from the "File -> New Project" dialog. And yes - I do have the MAUI workload installed in the Visual Studio installer.

It appears that the required workloads are not installed when you download visual studio.
Additionally, they cannot be found on nuget when attempting to use dotnet workload restore.

Steps to reproduce would be:
- Download Visual Studio 17.4.0 Preview 2.1
- Install the MAUI workload using the Visual Studio Installer
- Download a .NET 7 sample repo from https://github.com/dotnet/maui-samples
- Attempt to build


For me, the output of `dotnet workload list` is:
`
Installed Workload Id      Manifest Version                 Installation Source
-------------------------------------------------------------------------------
wasm-tools                 7.0.0-rc.1.22426.10/7.0.100      SDK 7.0.100-rc.1
runtimes-windows           7.0.0-rc.1.22426.10/7.0.100      VS 17.4.32916.344
maccatalyst                15.4.1006-rc.1/7.0.100-rc.1      VS 17.4.32916.344
ios                        15.4.1006-rc.1/7.0.100-rc.1      VS 17.4.32916.344
`

dotnet workload search` is:
`
Workload ID                Description
----------------------------------------------------------------------------------------------
ios                        .NET SDK Workload for building iOS applications.
maccatalyst                .NET SDK Workload for building macOS applications with MacCatalyst.
runtimes-windows           workloads/runtimes-windows/description
runtimes-windows-net6      workloads/runtimes-windows-net6/description
tvos                       .NET SDK Workload for building tvOS applications.
wasm-experimental          workloads/wasm-experimental/description
wasm-tools                 .NET WebAssembly build tools
wasm-tools-net6            .NET WebAssembly build tools
`

Notably, there is no maui workload like there is in previous versions.

**Comment by yiszza** [comment]
+1

**Comment by neoayi** [comment]
+1

**Comment by migueBarrera** [comment]
Same issue

**Comment by davefxy** [comment]
Same issue. Cant run net6 compiles either. Microsoft.Maui.Dependencies (6.0.540) wont load.

**Comment by virzak** [comment]
This workaround helps getting the workloads

```
dotnet workload restore --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json
```

**Comment by codemonkey85** [comment]
@virzak It doesn't seem to help me...
![image](https://user-images.githubusercontent.com/1414036/191570354-bfb4e4f0-f20b-47e4-b025-13b001763479.png)

**Comment by davefxy** [comment]
@virzak  Didnt help me either

**Comment by virzak** [comment]
Same here actually. It helped download ios stuff but then started throwing.


```
🚀  dotnet workload restore
Installing workloads: maui-android maui-tizen

Workload installation failed: One or more errors occurred. (The given key 'Microsoft.iOS.Sdk' was not present in the dictionary.)
```

```
🚀  dotnet workload list

Installed Workload Id      Manifest Version                  Installation Source
------------------------------------------------------------------------------------------------
ios                        15.4.1006-rc.1/7.0.100-rc.1       SDK 7.0.100-rc.1, VS 17.4.32916.344
maccatalyst                15.4.1006-rc.1/7.0.100-rc.1       SDK 7.0.100-rc.1, VS 17.4.32916.344
maui-windows               7.0.0-rc.2.6710/7.0.100-rc.1      VS 17.4.32916.344
maui-maccatalyst           7.0.0-rc.2.6710/7.0.100-rc.1      VS 17.4.32916.344
maui-ios                   7.0.0-rc.2.6710/7.0.100-rc.1      VS 17.4.32916.344
maui-android               7.0.0-rc.2.6710/7.0.100-rc.1      VS 17.4.32916.344
android                    33.0.0-rc.1.152/7.0.100-rc.1      VS 17.4.32916.344
wasm-tools                 7.0.0-rtm.22470.2/7.0.100         VS 17.4.32916.344

Use `dotnet workload search` to find additional workloads to install.

Unhandled exception: System.Collections.Generic.KeyNotFoundException: The given key 'Microsoft.iOS.Sdk' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.<>c__DisplayClass32_0.<GetUpdatedWorkloads>b__2(WorkloadPackId p)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.GetUpdatedWorkloads(WorkloadResolver advertisingManifestResolver, IEnumerable`1 installedWorkloads)+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Microsoft.DotNet.Workloads.Workload.List.WorkloadListCommand.Execute()
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Cli.Parser.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__17_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass7_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by davefxy** [comment]
I see the same thing. I have a 2nd PC that I updated VS 2022 today, and I am not seeing the same problems. I am trying to determine the differences.

**Comment by Redth** [comment]
We are actively investigating this issue and have an idea of the problem - basically the version generated for the .msi installer created for the packages was creating an older version than the dotnet CLI tools expect to see.

We are working on this and will be publishing updated packages to make a workaround available as quickly as we can.

**Comment by florianwachs** [comment]
Great! can't waut to try it

**Comment by foximoxi** [comment]
What is worse, VS Preview 2.1 with installed RC1 does not allow to build 6.0 MAUI applications.
I see constant error in MAUI build:

Error	NETSDK1147	To build this project, the following workloads must be installed: maccatalyst
To install these workloads, run the following command: dotnet workload restore	SCF	C:\Program Files\dotnet\sdk\6.0.401\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets	38	

Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-ios, net6.0-maccatalyst

Did you ever try VS 2022 and VS 2022 Preview installed together with both 6.0/7.0 RC1?

**Comment by SunshineSpring666** [comment]
Tested on latest VS Preview 2.1, it works ok on Windows.
Note **the Windows SDK Build Tool NuGet Package is also updated to the latest preview version 
(skipping the constraint shown in Nuget package installer by installing via dotnet CLI command),
hope this constraint to 22000 version can be removed officially.**

**Comment by SunshineSpring666** [comment]
Hi @Redth,
When targeting to .NET 7 runtime, MAUI project automatically installs many Xamarin-related NuGet Packages, including:
Xamarin.AndroidX.Browser, Xamarin.Android.Legacy.Support.V4, etc.
See the attached image for details.
![MAUI_AddedXamarinNugetPackages](https://user-images.githubusercontent.com/42401603/191671671-b85ef320-1d95-4bc5-aadf-54797ca22703.png)

**Comment by SunshineSpring666** [comment]
"Implicit Referenced By SDK", can't be removed. Quite weird, since this is a MAUI project.

![ImplicitReferenceBySDK](https://user-images.githubusercontent.com/42401603/191693963-1434479c-3733-4f72-8b41-8cf4f5877cb6.png)

**Comment by florianwachs** [comment]
> What is worse, VS Preview 2.1 with installed RC1 does not allow to build 6.0 MAUI applications. I see constant error in MAUI build:
> 
> Error NETSDK1147 To build this project, the following workloads must be installed: maccatalyst To install these workloads, run the following command: dotnet workload restore SCF C:\Program Files\dotnet\sdk\6.0.401\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets 38
> 
> Error NU1012 Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-ios, net6.0-maccatalyst
> 
> Have you ever tried VS 2022 and VS 2022 Preview installed together with both 6.0/7.0 RC1?

Can report the same, Vs 2022 is now broken too on my machine with maui 6.

**Comment by miadey** [comment]
Workaround that I used and worked for me. Seem that Dotnet get mixed-up when multiple framework are installed.

in bash: 
Locate Dotnet folder with Find, the one withthe sdk and runtume folder.
rm -rf Dotnet.
Reinstall sdk and runtime
You’ll get a fresh 6 and 7 installation
Worked for me

**Comment by Mephisztoe** [comment]
I too ran into this problem after upgrading Visual Studio to 17.4.0 Preview 2.1.

However, I then tried restoring the workloads as suggested above with this command:
>> dotnet workload restore --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json

The command sucessfully installed everything:
Welcome to .NET 7.0!
---------------------
SDK Version: 7.0.100-rc.1.22431.12

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
Installing workloads:

The machine has a pending reboot. Installation will continue, but you may need to restart.
Downloading microsoft.net.sdk.android.manifest-7.0.100-rc.1.msi.x64 (33.0.0-rc.1.152)
Installing Microsoft.NET.Sdk.Android.Manifest-7.0.100-rc.1.33.0.0-rc.1.152-x64.msi ..... Done
Downloading microsoft.net.sdk.ios.manifest-7.0.100-rc.1.msi.x64 (15.4.1031-rc.1)
Installing Microsoft.NET.Sdk.iOS.Manifest-7.0.100-rc.1.15.4.1031-rc.1-x64.msi .... Done
Downloading microsoft.net.sdk.maccatalyst.manifest-7.0.100-rc.1.msi.x64 (15.4.1031-rc.1)
Installing Microsoft.NET.Sdk.MacCatalyst.Manifest-7.0.100-rc.1.15.4.1031-rc.1-x64.msi ..... Done
Downloading microsoft.net.sdk.macos.manifest-7.0.100-rc.1.msi.x64 (12.3.1031-rc.1)
Installing Microsoft.NET.Sdk.macOS.Manifest-7.0.100-rc.1.12.3.1031-rc.1-x64.msi ..... Done
Downloading microsoft.net.sdk.maui.manifest-7.0.100-rc.1.msi.x64 (7.0.0-rc.2.6736)
Installing Microsoft.NET.Sdk.Maui.Manifest-7.0.100-rc.1.7.0.0-rc.2.6736-x64.msi ..... Done
Downloading microsoft.net.sdk.tvos.manifest-7.0.100-rc.1.msi.x64 (15.4.1031-rc.1)
Installing Microsoft.NET.Sdk.tvOS.Manifest-7.0.100-rc.1.15.4.1031-rc.1-x64.msi ..... Done
Downloading microsoft.net.workload.mono.toolchain.net6.manifest-7.0.100.msi.x64 (7.0.0-rtm.22472.8)
Installing Microsoft.NET.Workload.Mono.ToolChain.net6.Manifest-7.0.100.7.0.0-rtm.22472.8-x64.msi ..... Done
Downloading microsoft.net.workload.mono.toolchain.net7.manifest-7.0.100.msi.x64 (7.0.0-rtm.22472.8)
Installing Microsoft.NET.Workload.Mono.ToolChain.net7.Manifest-7.0.100.7.0.0-rtm.22472.8-x64.msi ..... Done
Downloading microsoft.net.workload.emscripten.net6.manifest-7.0.100.msi.x64 (7.0.0-rtm.22468.1)
Installing Microsoft.NET.Workload.Emscripten.net6.Manifest-7.0.100.7.0.0-rtm.22468.1-x64.msi ..... Done
Downloading microsoft.net.workload.emscripten.net7.manifest-7.0.100.msi.x64 (7.0.0-rtm.22468.1)
Installing Microsoft.NET.Workload.Emscripten.net7.Manifest-7.0.100.7.0.0-rtm.22468.1-x64.msi .... Done

Successfully installed workload(s) .

I then did a Clean project, deleted bin and obj folder and am finally rebooting my machine n...

**Comment by Mephisztoe** [comment]
ow. Well didn't work out that way. Now, Visual Studio does not recognize my .NET MAUI project anymore and suggests installing _extra components for a full development experience_ instead. However, when trying to do so, it also explains that everything is already in place.

Result: My .NET MAUI setup is completely broken... :(

**Comment by davidbuckleyni** [comment]
Same issue with me getting kind of tired with MS working on staff only builds and releasing stuff that is not customer ready !

![image](https://user-images.githubusercontent.com/5619229/192052782-71169f3c-1bcb-4142-a1ee-7e8ba57e6cfc.png)

**Comment by Redth** [comment]
We have some newer packages we will publish soon after a bit more validation.

If anyone is willing to try and install them from the staging feed, you can try the following commands:

```
dotnet --verson
```
Make sure you are running dotnet commands within the context of `7.0.100-rc.1`

> NOTE: The context matters when you run these commands and it's possible if you run them from a current directory that has the sdk version pinned from a global.json file, things will not run as you might be expecting. This goes for all dotnet commands!

Run the following command exactly:
```
dotnet workload install maui android ios maccatalyst macos --from-rollback-file https://maui.blob.core.windows.net/metadata/rollbacks/net7.0-rc.1.2.json --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json --source https://api.nuget.org/v3/index.json
```

If you try this, please report your results!

**Comment by Mephisztoe** [comment]
Tried that, didn't work. There's some signature missing:

![image](https://user-images.githubusercontent.com/5309613/192058351-67cc4428-3190-4faa-9c06-f51993d3531c.png)

**Comment by Redth** [comment]
> Tried that, didn't work. There's some signature missing:
> 
> ![image](https://user-images.githubusercontent.com/5309613/192058351-67cc4428-3190-4faa-9c06-f51993d3531c.png)
> 
> Added --skip-sign-check as suggested by @jamesmontemagno
> 
> Failed anyway: ![image](https://user-images.githubusercontent.com/5309613/192058560-efd06823-eec3-48d2-a64f-f2682ffbfe1e.png)

That version it's looking for was never published to nuget, so presumably at some point you did an install/update with additional package sources in the context of that update that aren't included now.

I'd rather not confuse this thread with this side issue, please follow up with James, I have some ideas.

**Comment by Conbag93** [comment]
I've been struggling this for the past few days, but I persevered after reading some of the comments here. I got it fixed in the end, but there are clearly some bugs to be ironed out with the overall process.

Here is what I experienced:
If you have the .Net 7 RC1 SDK installed, and then you install Visual Studio 17.4.0 Preview 2.1 - `dotnet workload list` would look something like this (note the ugly error):

```
Installed Workload Id      Manifest Version                  Installation Source
------------------------------------------------------------------------------------------------
ios                        15.4.1006-rc.1/7.0.100-rc.1       SDK 7.0.100-rc.1, VS 17.4.32916.344
maccatalyst                15.4.1006-rc.1/7.0.100-rc.1       SDK 7.0.100-rc.1, VS 17.4.32916.344
macos                      12.3.1029-rc.1/7.0.100-rc.1       SDK 7.0.100-rc.1
runtimes-windows           7.0.0-rtm.22471.3/7.0.100         VS 17.4.32916.344
maui-windows               7.0.0-rc.1.6683/7.0.100-rc.1      VS 17.4.32916.344
maui-maccatalyst           7.0.0-rc.1.6683/7.0.100-rc.1      VS 17.4.32916.344
maui-ios                   7.0.0-rc.1.6683/7.0.100-rc.1      VS 17.4.32916.344
maui-android               7.0.0-rc.1.6683/7.0.100-rc.1      VS 17.4.32916.344
android                    33.0.0-rc.1.151/7.0.100-rc.1      VS 17.4.32916.344

Use `dotnet workload search` to find additional workloads to install.

Unhandled exception: System.Collections.Generic.KeyNotFoundException: The given key 'Microsoft.iOS.Sdk' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.<>c__DisplayClass32_0.<GetUpdatedWorkloads>b__2(WorkloadPackId p)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.GetUpdatedWorkloads(WorkloadResolver advertisingManifestResolver, IEnumerable`1 installedWorkloads)+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Microsoft.DotNet.Workloads.Workload.List.WorkloadListCommand.Execute()
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Cli.Parser.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__17_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass7_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

In the scenario above, it seems to be necesary to manually uninstall ios, maccatalyst and macos workloads like so:

```
dotnet workload uninstall ios
dotnet workload uninstall maccatalyst
dotnet workload uninstall macos
```

Once done, you can install using the command posted by @Redth earlier (with the skip signature flag enabled:
```
dotnet workload install maui android ios maccatalyst macos --from-rollback-file https://maui.blob.core.windows.net/metadata/rollbacks/net7.0-rc.1.2.json --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json --source https://api.nuget.org/v3/index.json --skip-sign-check
```

After doing this I was able to build.

Additionally - in case it helps anyone else - I did find strange behaviour when attempting to install Download Visual Studio 17.4.0 Preview 2.1 **without** having .Net 7 RC1 installed beforehand. 

In this scenario, I found that "maui" would not appear in my workload list during `dotnet workload search` - even when I had the "MAUI" workload checked in the VS installer.

As a result, atempting to use the suggeted fix above would not work and would display "Workload id maui is not recognized".

Using the "Repair" tool in the Visual Studio Installer was necessary to make the "maui" workload appear.
It is odd that this would be required for a 'fresh' install - but that was my experience.

**Comment by davidbuckleyni** [comment]
![image](https://user-images.githubusercontent.com/5619229/192481906-2851addb-741d-44e5-a1d8-df859b8e96fa.png)


That seemed to have better sucess will try running the app now

**Comment by davidbuckleyni** [comment]
Still getting futher issues here 

![image](https://user-images.githubusercontent.com/5619229/192483415-dd73b787-73fc-4f2d-aaec-697953be8dfd.png)

**Comment by Redth** [comment]
We've published the packages after validating they install and correct the specific issue where you installed a standalone .NET 7 RC1 SDK before installing VS 17.4 P2.1.

Until we're able to ship an update with the next VS 17.4 preview, you can work around it with the following:

```
dotnet --verson
```
Make sure you are running dotnet commands within the context of `7.0.100-rc.1` (ideally the exact version is `7.0.100-rc.1.22431.12`) 

> NOTE: The context matters when you run these commands and it's possible if you run them from a current directory that has the sdk version pinned from a global.json file, things will not run as you might be expecting. This goes for all dotnet commands!

Run the following command exactly:
```
dotnet workload install maui android ios maccatalyst macos
```

Thanks for your patience!

**Comment by Conbag93** [comment]
> We've published the packages after validating they install and correct the specific issue where you installed a standalone .NET 7 RC1 SDK before installing VS 17.4 P2.1.
> 
> Until we're able to ship an update with the next VS 17.4 preview, you can work around it with the following:
> 
> ```
> dotnet --verson
> ```
> 
> Make sure you are running dotnet commands within the context of `7.0.100-rc.1` (ideally the exact version is `7.0.100-rc.1.22431.12`)
> 
> > NOTE: The context matters when you run these commands and it's possible if you run them from a current directory that has the sdk version pinned from a global.json file, things will not run as you might be expecting. This goes for all dotnet commands!
> 
> Run the following command exactly:
> 
> ```
> dotnet workload install maui android ios maccatalyst macos
> ```
> 
> Thanks for your patience!

Hello - with reference to my earlier comment - based on my experience - I do not think command alone is enough.

If you have .NET 7 RC1 pre-installed, then running `dotnet workload list` throws a Dictionary exception.
The same exception is thrown when running this command, and the workloads are not installed.

I had to manually remove the offending workloads before `dotnet workload install maui android ios maccatalyst macos` would run without issues.

**Comment by florianwachs** [comment]
worked for me, thanks a lot for your work!

**Comment by matt-goldman** [comment]
Since installing the latest Visual Studio preview I've been getting this error:
<img width="379" alt="image" src="https://user-images.githubusercontent.com/19944129/193431326-4279dbda-1dfc-4abb-9ca2-acc69e9f57d7.png">
I've tried installing the tizen workload, removing tizen as a TFM from my project, and I've tried running `dotnet workload restore` as per the suggestion with the error.
I've also tried all the suggestions here to no avail. I went the brute force approach and uninstalled every version of Visual Studio, every dotnet workload, and then installed a fresh instance of Visual Studio 2022 Enterprise. And I still get this error.

I think I've hit reinstall Windows territory. Is there anything else I can try first?

**Comment by davidbuckleyni** [comment]
Thid is still not solved

**Comment by tsjdev-apps** [comment]
I'm still struggeling. I've already tried to uninstall Visual Studio and also Visual Studio Preview from my Windows machine. After installing only Visual Studio again, I encountered the same issue. The only workaround for me is to remove the `net6.0-ios` and `net6.0-maccatalyst` from the `csproj` file. So is there any other workaroung for *.NET 6.0* MAUI apps?

**Comment by davefxy** [comment]
I believe you can use the global.json file. Put it in the project directory (same place as csproj). This will indicate to VS that the project should use Net 6. In this file put the following:
'{
    "sdk": {
      "version": "6.0.400",
      "rollForward": "latestMinor"
    }
  }'
