### ISSUE TITLE
FlexLayout doesn't work with BindableLayout

### ISSUE THREAD

**Issue by byme8** [dotnet/maui#10546]
### Description

The FlexLayout doesn't work with BindableLayout.

### Steps to Reproduce

1. Run the app.
2. Press the button.

On Windows fails with the exception "A cycle occurred while laying out the GUI."
On Android nothing happens

### Link to public reproduction project repository

https://github.com/byme8/expMaui3

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Windows 10.0.17763.0, Android 11

**Comment by byme8** [comment]
Repository was private, made it public

**Comment by swordream** [comment]
Same problem! Is there a solution?

**Comment by hartez** [comment]
Fixed by #13216

**Comment by byme8** [comment]
@hartez, how can I verify it? I have tried the latest Visual Studio 17.6.0 Preview 1.0 and the issue is still here.

**Comment by hartez** [comment]
> @hartez, how can I verify it? I have tried the latest Visual Studio 17.6.0 Preview 1.0 and the issue is still here.

Did you install the .NET 8 preview? The fix is available in the first .NET 8 preview, but it hasn't hit any of the .NET 7 versions yet. It should be in the next .NET 7 service release.
