### ISSUE TITLE
[Windows] MAUI Controls does not render anymore correctly after latest update

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#11045]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Windows-MAUI-Controls-does-not-render-/10179075)._

---
Hi.  
My project worked fine with Preview 3.0. Now, in Preview 4.0 the controls are not anymore on the position which worked on Preview 3.0. The Border does not Fill the grid, Image is now on the left with 60, the labels as well. What is happening with this version?!

Edit: I've used rollback feature from Visual Studio Installer, downgraded to Preview 3.0 version, and now everything is ok. So, I think I will stay to Preview 3.0 till you will see what is going on with the position of controls and why they changed without any code change.

---
#### Feedback Bot on 10/23/2022, 07:11 PM: 

(private comment, text removed)
#### Vali Maties on 10/25/2022, 05:20 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by hartez** [comment]
This is likely fixed by #10768, and should be working in the next release.

**Comment by wkfry** [comment]
I opened a similar issue. I installed the latest VS Preview 6 today (with .NET 7.0.100-rc.2.22477.23) and the problem still exists for me.
