### ISSUE TITLE
ListView ViewCell content disappears when the application enters the foreground

### ISSUE THREAD

**Issue by ultra133** [dotnet/maui#11640]
### Description

A simple page consists only a ListView, which has a ViewCell as DataTemplate. 

When the app on iOS (whether device or simulator) goes to the background and then back to the foreground, the content of the CellViews disappears. Only empty cells remain.

### Steps to Reproduce

1. Create a New .NET MAUI App from the template
2. Replace the content of MainPage.xaml
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="ListTest.MainPage">

    <ContentPage.ToolbarItems>

    </ContentPage.ToolbarItems>

    <ListView>

        <ListView.ItemsSource>
            <x:Array Type="{x:Type x:String}">
                <x:String>One</x:String>
                <x:String>Two</x:String>
                <x:String>Three</x:String>
            </x:Array>
        </ListView.ItemsSource>

        <ListView.ItemTemplate>
            <DataTemplate x:DataType="x:String">
                <ViewCell>
                    <Grid
                        ColumnDefinitions="80,*">
                        <Button Text="{Binding .}"/>
                    </Grid>
                </ViewCell>
            </DataTemplate>
        </ListView.ItemTemplate>

    </ListView>

</ContentPage>
```

3. Run the app on iOS Simulator 16.0. The app shows a list with three lines of  buttons.
4. Send the app to the background. Do not close the app!
5. Pull the app back to the foreground

### What should happen:
The app looks like before.

### What happens instead:
The three lines are still visible, but the buttons disappear.

### Link to public reproduction project repository

https://github.com/ultra133/ListTest.git

### Version with bug

7.0 (current)

### Last version that worked well

This worked with Xamarin! So it's a big issue when migrating to .NET MAUI.

### Affected platforms

iOS

### Affected platform versions

iOS 16

### Did you find any workaround?

No

**Comment by ultra133** [comment]
### Link to repository
https://github.com/ultra133/ListTest.git

**Comment by petermauger** [comment]
This is almost CERTAINLY linked to my issue https://github.com/dotnet/maui/issues/11598

I don't see how this isn't getting some serious, and prioritised, attention. 

Can't use ListView in app without random failures is a MASSIVE blocker for my app that is otherwise ready to be released to our user base. 

net 7.0 is 'production ready' apparently so this should be getting dealt with at way higher priority than 'backlog' @rachelkang ???

**Comment by petermauger** [comment]
@jsuarezruiz @rachelkang If someone can help me get a VS project setup so I can actually breakpoint and debug the MAUI code behind this then I'll put together and submit a PR for it myself. I can't seem to put together a MAUI app project that uses the repository projects instead of the packaged frameworks?

**Comment by ultra133** [comment]
We must conclude that migrating existing Xamarin apps to MAUI is not practical at this time, and will not be in the foreseeable future.
New projects will have to abandon the use of ListView and use CollectionView instead.

**Comment by sstahurski** [comment]
Verified this is still an issue at this time, I've only been able to reproduce this on iOS.
I've also had issue with scrolling as well, where listview items as well in larger lists disappear ( i.e they are there but the contents are not displayed.)

**Comment by FBonini22** [comment]
Still having the same issue as well, only on iOS.

**Comment by knprice** [comment]
March 1st, still having this issue on iOS.

**Comment by Matmork** [comment]
There is this https://github.com/dotnet/maui/pull/13669

**Comment by arctouch-kseniyagaripova** [comment]
March, 28.
Are there any chances that ListView will be usable?

**Comment by nicjay** [comment]
I am sorry but this is not a "move to backlog" issue. I was shocked to see this issue was created back in November with no response since.

1) DIsplaying lists is a very common app function.
2) Sending apps to the background is a very common user action.

One might recommend that we could use CollectionView, but frankly, that also has a whole separate set of issues that made me switch back to ListView.

**Comment by jonathanpeppers** [comment]
Those experiencing this issue, is `x:Array` and `x:String` always involved?

* https://github.com/dotnet/maui/pull/14546

If you have an example that hit this problem, and are not using these, let me know.

I will test, but I think #14546 likely fixes it.

**Comment by ultra133** [comment]
Jonathan, this problem here is not related to your x:Array patch.
The problem described here also occurs in debug mode and independently of the items source. The x:Array was used for demonstration purposes only.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 1.0. Repro on iOS 16.4 with above provided Project:
[ListTest.zip](https://github.com/dotnet/maui/files/11684575/ListTest.zip)

Pull the app back to the foreground, the buttons disappear.
![image](https://github.com/dotnet/maui/assets/97647558/31886d7e-23e2-4180-9d22-f5c69e0cab03)

**Comment by xufeitt** [comment]
TableView use ViewCell have the same problem,   IOS and more than 2 viewcells will raise this problem, android is ok.

**Comment by TamerIrdais** [comment]
This is also an issue on my side as well on latest VS2022 17.6.2.
The only workaround I found is to use ListViewCachingStrategy.RecycleElement but this mode is very slow so its not that good of an option when having ListView with moderate to large number of items.

**Comment by RogueJin** [comment]
I have the similar issue on MacCatalyst when scrolling listview, viewcell content disappears. dotnet version 7.0.302.

**Comment by mnidhk** [comment]
Just started with template MAUI to port my XF apps. Tried one page to convert to maui. A settings page with a tableview with 10 view cells. Same issue. When navigating away from my app and back, most of the cells are gone, empty cells are left!

**Comment by peterbersani** [comment]
As a work-around, I am using a CollectionView. The problem appears to be with the ViewCell in the DataTemplate within a ListView.ItemTemplate. CollectionView ItemTemplates do not use ViewCell.

**Comment by HealthMode** [comment]
I was struggling with this issue and `CachingStrategy="RecycleElement"` fixed it on the XAML of the list view

**Comment by MuhSchaf** [comment]
Thanks @TamerIrdais and @HealthMode. This workaround worked for me.

**Comment by jfversluis** [comment]
I see there is #15036 that was merged that might have to do with this. Is there anyone that is already on the .NET 8 preview bits that might confirm if the problem still persists there? This change should be available in .NET 8 preview 5.

**Comment by ultra133** [comment]
Gerald, I don't think .NET 8 is yet available on the Visual Studio for Mac preview channel, is it?

**Comment by chema-code** [comment]
> I was struggling with this issue and `CachingStrategy="RecycleElement"` fixed it on the XAML of the list view

Thanks, worked for me

**Comment by PureWeen** [comment]
I tested this against .NET8 and it appears fixed

I'm guessing it's fixed by
https://github.com/dotnet/maui/pull/15036

**Comment by Vogel9696** [comment]
Hello guys, i still have this issue.

If i am using Listview with ViewCell and ViewCell MenuItems.
When i am deleting item without CachingStrategy="RecycleElement" when another items are blank.
When i am deleting item with CachingStrategy="RecycleElement" when the item are not blank but the MenuItem jumps to another Item and is opened without user swipe.

I dont wanna use SwipeView instead of ViewCell.MenuteItem because it looks not good :/
