### ISSUE TITLE
Images with CachingEnabled are never updated

### ISSUE THREAD

**Issue by Dreambound131** [dotnet/maui#12376]
Hello, I found an issue with cached images in MAUI .NET7 Android (not tested on iOS).

Basically, when using UriImageSource the image get cached and then is never updated (according to the documentation default cache should be 1 day).
I tried changing CacheValidity property to various values but the behavior is always the same.

Setting CachingEnabled to false work as expected, no image caching so the image is updated every time.

I first discovered this issue on my main app, but it appear even on a clean MAUI project.
The easiest way I found to test this issue was starting a new MAUI project and simply changing the dot net bot image to point to https://picsum.photos/200 that returns a different image with every request.

```
<Image
    SemanticProperties.Description="Cute dot net bot waving hi to you!"
    HeightRequest="200"
    HorizontalOptions="Center">           
        <Image.Source>               
            <UriImageSource CacheValidity="00:00:01:00"
                            CachingEnabled="True"                          
                            Uri="https://picsum.photos/200" />                
        </Image.Source>
</Image>
```

Using the code above I expected the app to update the image if closed and re-opened it after more than a minute, but this doesn't happen (the image is not updated even after several days).

Can you help me? I don't know if I'm doing/expecting something wrong or if it is a bug

Thank you

**Comment by Eilon** [comment]
I believe this is currently how it's designed, but there's an issue to track improvements to this area:

* Add clear image caching APIs #4766

**Comment by sbkrishnan2506** [comment]
Hello,

I am also struck with that issue, we released the app with the default values, if we change any image with the URL it is not updating, we need to fix and release another version by disabling the cache.
Any update on this fix?

**Comment by homeyf** [comment]
This issue does not repro on Visual Studio Enterprise 17.8.0 preview 3.0. Not repro on windows platform with sample code.
![image](https://github.com/dotnet/maui/assets/82450723/02381285-bdac-4efb-a704-fbeef7196b8c)

**Comment by Dreambound131** [comment]
Hi @homeyf I confirm that on windows everything works fine, but the issue is still present at least on Android platform

**Comment by ThiagoFrancischini** [comment]
Still not working on Android

**Comment by Stefan171086** [comment]
Can confirm that the issue still exists with NET8 on Android!!
