### ISSUE TITLE
[WinUI] CarouselView / CollectionView : Control events never fire

### ISSUE THREAD

**Issue by Stedy59** [dotnet/maui#15914]
### Description

Back in January, I opened an issue indicating a lack of "Scrolled" events.  Pointing out a line of code that, upon creation, removed a critical event handler, as opposed to adding it.

[#12725](https://github.com/dotnet/maui/issues/12725#issue-1536981044)

This line of code was marked fixed and the issue was closed in 8.0.0-preview.4.8333...  I tested that release, and the Scrolled event was not being fired. In addition, the only event that fired was the ScrollTo event. Since the code that sets the ScrollViewer properties relies on this UI.Xaml control [ScrollViewer] to be found, ScrollBarVisibility, ScrollMode, SnapPointsType, SnapPointsAlignment,, PeekAreaInsets, ScrollInertiaEnabled and SwipeEnabled, including event notification are not set.

**Oh, and BTW, since the WinUI CollectionView uses the exact same base, "ViewHandler<TItemsView, ListViewBase>", the same symptoms occur in this control on WinUI.**

These "symptoms" are a result of the fact that the ScrollViewer is never found! Even with the latest .net 8.0.0-preview.5

In that first issue reported, I attached an "AppendToMapping" class that fixed the "ScrollViewer" issues, and for the most part, it now worked properly. The issue I ran into was, when using a TemplateSelector (shown below), the first item would never display properly. (My implementation of a "TabView" control...)

`this._contentContainer.ItemTemplate = new DataTemplate(() => new ContentView()
          .Bind(ContentProperty, "TabContent")
          .Bind(View.HeightRequestProperty, path: "TabContentHeight", source: this)
          .Bind(View.WidthRequestProperty, path: "TabContentWidth", source: this));`

I attempted to use a CollectionView in its place, the individual items displayed correctly, but the needed event wouldn't fire.

So I took the "AppendToMapping" code and used it on the CollectionView, essentially creating a CarouselView... since the underlying base is the same. It works!!!

This brings me to my last point... Since .net Maui is a framework provided for developers to build with... why would I encounter an EventArgs class with Internal constructors? "CurrentItemChangedEventArgs", "PositionChangedEventArgs", "SelectionChangedEventArgs", etc ?????

### Steps to Reproduce

1. Run the .net Maui samples!!! 

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK - all

### Did you find any workaround?

Write an "AppendToMapping" class to find the ScrollViewer control.

**Comment by Stedy59** [comment]
Here is my implementation code for anyone interested.

[MauiCarouselView.MauiCollectionView.zip](https://github.com/dotnet/maui/files/11897936/MauiCarouselView.MauiCollectionView.zip)

**Comment by drasticactions** [comment]
That fix was brought into Main, net8.0, and net7.0 so it should be in the current release. Your original issue pointed to the event handler issue, but didn't have a repro or what you expected to happen once it was changed, so my guess was they updated it without knowing what issue you were having in context of your app.

Can you create a reproduction project showing the issue and what you wish would happen? Thank you for the implementation code, but without the context of how you're using it or what it is, I'm not sure how to use it to reproduce what you're seeing or what you're expecting.

> This brings me to my last point... Since .net Maui is a framework provided for developers to build with... why would I encounter an EventArgs class with Internal constructors? "CurrentItemChangedEventArgs", "PositionChangedEventArgs", "SelectionChangedEventArgs", etc ?????

My guess would be that they are not intended for you to use. They're events that are fired from the MAUI Framework and you consume the events, but you don't create them yourself and therefore don't create the event arguments that it uses.

**Comment by samhouts** [comment]
I believe that the Scrolled events are now fixed in 8.0-preview6 and 7.0.92-SR7, but both CollectionView and CarouselView need a lot of attention on Windows. Thank you, @Stedy59!

**Comment by Stedy59** [comment]
> I believe that the Scrolled events are now fixed in 8.0-preview6 and 7.0.92-SR7, but both CollectionView and CarouselView need a lot of attention on Windows. Thank you, @Stedy59!

Yes, the "Scrolled" event now fires... but the other symptoms are still present. I am putting together a sample project that shows the issues, in the context of "dynamic TemplateSelectors"... @samhouts  THANK YOU for looking into this.

**Comment by Stedy59** [comment]
@samhouts - I created a new issue for the layout problems as this was pointed at the events not firing. I created an elaborate repo to show/assist you and your team members. Thank you, @samhouts!

https://github.com/dotnet/maui/issues/16322

**Comment by samhouts** [comment]
Duplicate of #12725

**Comment by samhouts** [comment]
We'll close this one and focus on https://github.com/dotnet/maui/issues/16322. Thanks!!
