### ISSUE TITLE
Unable to Load iOS Platform Specific Image

### ISSUE THREAD

**Issue by adamzucchi** [dotnet/maui#16768]
### Description

The .NET MAUI Image control is unable to load an iOS platform specific image from the Platforms/iOS/Resources folder. On iOS only images from the shared Maui /Images folder are displayed.

### Steps to Reproduce

1. Create a new .NET MAUI solution
2. Add platform specific images to both the Android and iOS platform folders (On Android add dpi specific image to each dpi folder and on iOS add an @1x, @2x, and @3x version)
2a. In the referenced repro project note that all images from step 2 have a text marking on them making them unique so later on we can tell what is/isn't working properly
3. Also add a high resolution version of the image from step 2 to the shared Maui Images folder (this image in the repro project also has a text marking so it can be easily identified)
4. Go to the MainPage.xaml and add a new Image control to the UI and assign the Source property the .png name of the images that were added in steps 2 above
5. Run the app on an iOS and Android device and notice that the Android build is loading from the Android Platforms folder as expected while iOS is instead loading from the shared Images folder (the MauiImage file)

<img width="986" alt="Screenshot 2023-08-15 at 1 17 13 PM" src="https://github.com/dotnet/maui/assets/214052/1b3d5ccb-ca40-4902-9660-e9f59a617ac4">

If the shared MauiImage is deleted no image is displayed for iOS.

### Link to public reproduction project repository

https://github.com/adamzucchi/PlatformiOSImageBug

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

### Did you find any workaround?

I have not found any workarounds. I tried variations of assigning the source via an ImageSource but that also did not work. If the shared MauiImage is removed from the solution (and a clean and an app deletion is done from the iOS device due to caching) then no image shows up for iOS.

**Comment by mattleibow** [comment]
I see a large chunk of things where iOS things are being removed. What happens if you remove all this and let the default globs add it?

https://github.com/adamzucchi/PlatformiOSImageBug/blob/main/PlatformiOSImageBug/PlatformiOSImageBug/PlatformiOSImageBug.csproj#L79-L90

**Comment by adamzucchi** [comment]
> I see a large chunk of things where iOS things are being removed. What happens if you remove all this and let the default globs add it?
> 
> https://github.com/adamzucchi/PlatformiOSImageBug/blob/main/PlatformiOSImageBug/PlatformiOSImageBug/PlatformiOSImageBug.csproj#L79-L90

@mattleibow I removed that ItemGroup you referenced and ran this on both a physical iOS device and iOS sim and saw no change : ( 

I have pushed that change to the repro solution as well.

**Comment by AnnYang01** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0 using below Project (.NET 8.0), This issue repro on Windows 11, iOS 16.4 and Android 13.0-API33.
[MauiApp12.zip](https://github.com/dotnet/maui/files/12426074/MauiApp12.zip)
iOS 16.4
![image](https://github.com/dotnet/maui/assets/131441429/df78b671-7539-4080-80a7-ba215948f0c1)
Android 13.0-API33
![image](https://github.com/dotnet/maui/assets/131441429/e55df5dd-045e-442b-88ab-acb3100b0144)
Windows 11
![image](https://github.com/dotnet/maui/assets/131441429/4ed569fc-32ab-4871-90dc-ba8c81499fa6)

**Comment by rjhallock6** [comment]
Is there an update on this issue? From my research and trials, it still exists, and though it is not blocking, it does force deployment and a less-than-optimal app.
I'm using Visual Studio 2022, 17.8.6, version 4.8.09.037 and Android Google Pixel with Android 14, an iPhone 17.3, XCode 15.2, and Net8.0. Using the sample code identified as well as our own app I confirm the problem as originally described persists.

**Comment by yangshuxin199393** [comment]
It hasn't been updated in a while

**Comment by jfversluis** [comment]
This still happens with .NET 9 RC 1. I guess a workaround is to exclude the (.NET MAUI) image for a certain platform is you have provided the platform native images there.

It probably has to do with the order of processing things in Resizetizer.

**Comment by giuseppenovielli** [comment]
Try to add this to your .csproj ->
https://stackoverflow.com/questions/76541342/how-to-use-1x-2x-and-3x-png-images-in-maui-ios

`<PropertyGroup Condition="$(TargetFramework.Contains('-ios'))">
    <IPhoneResourcePrefix>Platforms/iOS/Resources</IPhoneResourcePrefix>
</PropertyGroup>`
