### ISSUE TITLE
[regression/8.0.0-preview.1.7762] TwoWay Binding does not work when value is changed from the source ViewModel

### ISSUE THREAD

**Issue by APopatanasov** [dotnet/maui#16849]
### Description

I have Entry and Text property with TwoWay Binding. When I change the property in the ViewModel the UI of the Entry is not updated. Even though the example is with Entry I think there is a major issue with the TwoWay Binding because I am observing this issue in multiple controls.

I've tested the my code against the latest changes in net 8 and the issue persists.

### Steps to Reproduce

1. Run the project.
2. Change the text in the Entry.
3. Click the Button that sets the Text of the Entry to empty in the ViewModel.
4. Notice how the text in the Entry itself is not changed.

### Link to public reproduction project repository

https://github.com/telerik/ms-samples/tree/main/Maui/MauiBindingIssue

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-preview.6.8686

### Affected platforms

iOS, Android, Windows, macOS

**Comment by jsuarezruiz** [comment]
Have done some tests on main branch and cannot reproduce the issue:

![issue-16849-ios](https://github.com/dotnet/maui/assets/6755973/5cd246c0-9d45-49dc-968f-5a7a15c7797b)
![issue-16849-droid](https://github.com/dotnet/maui/assets/6755973/d70413e1-5832-4e3c-8708-e269610e853f)

**Comment by ppluijten** [comment]
We have a similar issue: https://github.com/dotnet/maui/issues/16859
The difference for our case is that the clearing initially works, but after editing the text in the Entry the binding seems to break.

**Comment by samhouts** [comment]
I believe this was fixed by https://github.com/dotnet/maui/pull/16410

**Comment by APopatanasov** [comment]
@samhouts I've tested my sample against both the main and net8 branch and the mentioned PR doesn't fix it.

**Comment by PureWeen** [comment]
I'm able to reproduce this on preview7 @StephaneDelcroix 

I realize that our code should be calling `SetValue` with a more correct specificity but it looks like the new code no longer takes into account the following settings inside BO https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/BindableObject.cs#L490-L491

Is that by design? By default, before your change, TwoWay bindings didn't clear when calling `SetValue`, only OneWay bindings did. 

We have this issue to fix all of our setters https://github.com/dotnet/maui/issues/16654.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on Windows 11 .NET 8, Android 13.0-API33 and iOS 16.4 with below Project:
[MauiBindingIssue.zip](https://github.com/dotnet/maui/files/12449803/MauiBindingIssue.zip)
![ClearEntry](https://github.com/dotnet/maui/assets/97647558/2d49a14d-d6c0-450f-88f0-22190d26d43d)

**Comment by StephaneDelcroix** [comment]
@PureWeen we no longer clear the bindings in any case (iirc)

**Comment by StephaneDelcroix** [comment]
if the value is set with the correct specificity (fromHandler), everything's fine

```sharp
[Fact]
		//https://github.com/dotnet/maui/issues/16849
		public void ValueFromHandlerDoesntClearWayBinding()
		{
			var vm = new MockViewModel();
			var entry = new Entry { BindingContext = vm};
			entry.SetBinding(Entry.TextProperty, "Text", BindingMode.TwoWay);
			entry.SetValueFromRenderer(Entry.TextProperty, "foo");
			Assert.Equal("foo", vm.Text);
			vm.Text = "bar";
			Assert.Equal("bar", entry.Text);
			vm.Text = string.Empty;
			Assert.Equal(string.Empty, entry.Text);
		}
```

**Comment by samhouts** [comment]
Excellent. This means that this will be resolved when all of the tasks listed in https://github.com/dotnet/maui/issues/16654 are complete, which we will target for RC2.

I will close this one a s duplicate for now.

Thanks!

**Comment by samhouts** [comment]
Duplicate of #16654

**Comment by PureWeen** [comment]
Chatted with @StephaneDelcroix 

There's still an issue with TwoWay bindings that needs to be resolved. We'll hopefully get that fixed for RC1 but if not we have all these coming along https://github.com/dotnet/maui/issues/16654

which will fix our controls

**Comment by StephaneDelcroix** [comment]
there are 2 way to fix this, any one of the 2 would be enough, but both are required:
- Set the value from the handlers with SetValueFromRenderer (or SetValue with a FromHnadler specificity), that's what's done in #17036 
- change the behaviour of 2WayBindings so they always apply, even after a SetValue. This is counterintuitive, but it's the observed behaviour in other xaml platforms

**Comment by APopatanasov** [comment]
@PureWeen When you make a decision which option to choose please, take into account that the Entry scenario is one of many where the Binding is broken. 

We have multiple composite Templated controls (not native) where the Binding is not working. Let's take for example the ComboBox. This is a control with selection that has SelectedItem property. When the selection is performed through the UI we need to set the property from our code which is no longer working. 

Setting such properties with SetValueFromRenderer or SetValue with FromHandler specificity might not be so intuitive.
