### ISSUE TITLE
[iOS] Button in ScrollView has NO clicked effect

### ISSUE THREAD

**Issue by microspaze** [dotnet/maui#17132]
### Description

Button in iOS ScrollView has NO clicked effect when single tap, but long press is OK. 

**net7-ios & net8-ios both have this bug**

**Android does not have this bug.**

**Xamarin.Forms has this bug too.**

```
<VerticalStackLayout Spacing="10" Padding="30,30" VerticalOptions="Center">
	
	<ScrollView BackgroundColor="Aqua" HeightRequest="200">
		<Button HeightRequest="40" Text="Button In Scroll View"></Button>
	</ScrollView>
	
	<Button Text="Button Out Scroll View"></Button>
	
</VerticalStackLayout>
```

https://github.com/dotnet/maui/assets/17372096/548cac5a-515d-4cad-b2ff-bfc4b7338548

### Steps to Reproduce

1. Add a button to a ScrollView
2. Single tap the button, check the clicked effect
3. Long press the button, check the clicked effect

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.4

### Did you find any workaround?

NO WORKAROUND

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on iOS 16.4 .NET 8, Windows 11 and Android emulator with below Project:
[17132.zip](https://github.com/dotnet/maui/files/12533803/17132.zip)


For Windows 11 and Android emulator on .NET 8: Button in or out of ScrollView has No clicked effect.
![ClickEffect](https://github.com/dotnet/maui/assets/97647558/26aabe86-dc87-4798-997e-40f6de5fea98)

**Comment by minhiclick** [comment]
.net 8.0 Button has no effect when clicked.

**Comment by jsuarezruiz** [comment]
> .net 8.0 Button has no effect when clicked.

Try the latest version, fixed by https://github.com/dotnet/maui/pull/20412

**Comment by microspaze** [comment]
@jsuarezruiz This bug is still there. Buttons in scrollview have no single-clicked effect but have long press effect. Here's the test code.
[MauiButtonInScrollView.zip](https://github.com/user-attachments/files/15690927/MauiButtonInScrollView.zip)

**Comment by Pastajello** [comment]
Still happening on 8.0.70-ci.net8.24325.2

**Comment by andyzukunft** [comment]
I have this issue in my internal bug tracker for some time and it is still occuring in MAUI v8.0.70. It can be reproduced with the emulator running iOS v17.2.

In addition to no click effect the button itself does not react to single clicks within the red area as shown in the following graphics. Single clicks have no visual effects in the white area however they do initiate the binded Command.
![grafik](https://github.com/user-attachments/assets/c203cd63-7d05-462c-9965-8b90710ad12a)

I wanted to contribute this information as it seems no one mentioned it so far.

**Comment by Pastajello** [comment]
Still happening on 8.0.80

**Comment by Pastajello** [comment]
and still happening in 8.0.91 :D
I'll leave a nice trait for archeologists. Welp.
![image](https://github.com/user-attachments/assets/dc03ead9-08c4-49df-9b0c-26a1c07c299c)

**Comment by AdamEssenmacher** [comment]
Still happening in 9.0.120
