### ISSUE TITLE
[regression/8.0.0-preview.5.8529] [MAUI] The 'New Recipe' page will crash in landscape mode on iOS simulator

### ISSUE THREAD

**Issue by ZackYangyang** [dotnet/maui#17208]
### Description

The 'New Recipe' page will crash in landscape mode.

### Steps to Reproduce

1.Download the project https://github.com/rachelkang/recipeSearch and Locate it.
2.Tap on the 'My Recipes' tab to navigate to the 'My Recipes' page.
3.Tap on the 'New' button in the upper right-hand corner of the page to navigate to the 'New Recipe' page.
4.Rotate the emulator clockwise (to the right) to the landscape mode.

Actual result:
The 'New Recipe' page will crash in landscape mode
![image](https://github.com/dotnet/maui/assets/82210619/2b390281-8583-49bc-aeae-537c20f48ff3

### Link to public reproduction project repository

https://github.com/rachelkang/recipeSearch

### Version with bug

[8.0.0-preview.5.8529](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.5.8529)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

[8.0.0-preview.4.8333](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.4.8333)

### Affected platforms

iOS

**Comment by rachelkang** [comment]
Tested and I'm able to reproduce this issue in preview7, so it is not a p7 to rc1 regression

**Comment by ZackYangyang** [comment]
We performed supplementary tests to verify the regression:
Repro this issue when use Microsoft.Maui.Controls 8.0.0-nightly.9158+sha.cad4279216-azdo.8352477 on .NET SDK RC1/Preview7.
Repro this issue when use Microsoft.Maui.Controls 8.0.0-preview.7.8842 on .NET SDK RC1/Preview7.

**Comment by drasticactions** [comment]
The complete stacktrace is

```csharp
System.NullReferenceException: Object reference not set to an instance of an object.    at Microsoft.Maui.Controls.Handlers.Items.ItemsViewController`1[[Microsoft.Maui.Controls.CarouselView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].InvalidateMeasureIfContentSizeChanged()    at Microsoft.Maui.Controls.Handlers.Items.ItemsViewController`1[[Microsoft.Maui.Controls.CarouselView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ViewWillLayoutSubviews()    at Microsoft.Maui.Controls.Handlers.Items.CarouselViewController.ViewWillLayoutSubviews()    at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)    at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)    at Recipes.Program.Main(String[] args) in X:\Code\Work\recipeSearch\WhatToEat\Platforms\iOS\Program.cs:line 12} | System.NullReferenceException
```

And it seems specific to some devices and dimentions. It works on an iPhone 14, but not an iPhone 14 Pro Max.

And like @rachelkang, it happens in P7 too on the iPhone 14 Pro Max.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0 using below Project (8.0.0-preview.7.8842), This issue repro on  
iPhone 14 Pro Max and iPhone 14 Pro , not repro on iPhone 14.
[recipeSearch.zip](https://github.com/dotnet/maui/files/12554790/recipeSearch.zip)

Repro project: 
iPhone 14 Pro Max
![image](https://github.com/dotnet/maui/assets/97647558/59fcca9e-9ade-41f8-bd94-56a57dfe4530)
iPhone 14
![image](https://github.com/dotnet/maui/assets/97647558/e329c16f-68e7-4d53-b7c4-6920d5ff234e)

**Comment by DDHSchmidt** [comment]
Guys, we can now reliably reproduce this crash with the exact same stacktrace on our app.
This worked fine on Preview 7 and is now crashing constantly on RC 1. Is there a hidden agenda in Microsoft to make the experience continuously worse on iOS?
I thought progressing versions should improve the stability, not reduce it?

Reliably crashing with an iPad Pro (10.5 inches) on iOS 16.6.1

**Comment by samhouts** [comment]
Confirmed that this regressed between [8.0.0-preview.4.8333](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.4.8333) and [8.0.0-preview.5.8529](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.5.8529). This new code path was added in https://github.com/dotnet/maui/pull/14951. This PR was backported to NET 7 ([unreleased](https://github.com/dotnet/maui/pull/15652)), so the fix has to go in NET 7, too.

**Comment by QianaJiao** [comment]
Verified this bug was fixed and not repro. 
VSMac: 17.6.4 (17.6 build 472)
Microsoft.Maui.Controls: 8.0.0-nightly.9210+sha.39220c89b6-azdo.8394631
NET SDK: 8.0.100-rc.1.23455.8

**Comment by samhouts** [comment]
@QianaJiao I think you may have used a smaller simulator or device to test. This is still an issue on larger devices, like iPhone 14 Pro Max.

**Comment by PureWeen** [comment]
tracking additional work [here](https://github.com/dotnet/maui/issues/17494)
