### ISSUE TITLE
[regression/8.0.0-preview.1.7762] .NET 8 RC1 cannot use Syncfusion controls - SfListView gives System.TypeLoadException

### ISSUE THREAD

**Issue by Zack-G-I-T** [dotnet/maui#17265]
### Description

When trying to use SfListView in MAUI .NET 8 you get the following exception and the app crashes instantly.

System.TypeLoadException: 'Could not resolve type with token 010001d8 from typeref (expected class 'Style' in assembly '')'

I have added a dummy project here
https://github.com/Zack-G-I-T/SfListView.Net8Bug

### Steps to Reproduce

1. Run repo with all exceptions on
2. See exception

### Link to public reproduction project repository

https://github.com/Zack-G-I-T/SfListView.Net8Bug

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

No

### Relevant log output

```shell
System.TypeLoadException: 'Could not resolve type with token 010001d8 from typeref (expected class 'Style' in assembly '')'
```

**Comment by samhouts** [comment]
Duplicate of #17136

**Comment by samhouts** [comment]
@Zack-G-I-T  I marked this as a duplicate too hastily. At the time you opened this issue, RC1 was not yet released, it was only available in nightly builds. SyncFusion would need to release a new version of their controls that is built on the released RC1 in order to avoid this TypeLoad exception, since there was a significant change between previews. If you continue to experience this issue, please open a ticket with SyncFusion. Thanks!

**Comment by gabsamples6** [comment]
@samhouts - I did think at the beginning that were 2 diff issues- does not matter now, the important thing is that .net 8 has broken compatability with .net 7 and has left us in a really bad place as we cannot move to .net 8 till Syncfusion fixes the issues, which they wont till you go stable as part of the policy.. Any suggestions?

**Comment by samhouts** [comment]
You may want to contact SyncFusion to find out if they have preview builds available.

**Comment by jonathanpeppers** [comment]
Ok, this one got interesting!

Using ILVerify, we found:
```
## Syncfusion.Maui.Core.dll
[IL]: Error [ClassLoadGeneral]: [SfListView.Net8Bug/SfListViewBug/obj/Release/net8.0-android/android-arm/linked/Syncfusion.Maui.Core.dll : Syncfusion.Maui.Core.Internals.ListViewScrollViewHandler::CreatePlatformView()] Failed to load type 'Style' from assembly 'Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
[IL]: Error [ClassLoadGeneral]: [SfListView.Net8Bug/SfListViewBug/obj/Release/net8.0-android/android-arm/linked/Syncfusion.Maui.Core.dll : Syncfusion.Maui.Core.Hosting.DataGridScrollViewHandler::CreatePlatformView()] Failed to load type 'Style' from assembly 'Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
2 Error(s) Verifying SfListView.Net8Bug/SfListViewBug/obj/Release/net8.0-android/android-arm/linked/Syncfusion.Maui.Core.dll
```
Ok, so we decompiled Syncfusion's code:
```csharp
// Syncfusion.Maui.Core, Version=22.2.12.0, Culture=neutral, PublicKeyToken=null
// Syncfusion.Maui.Core.Internals.ListViewScrollViewHandler
internal class ListViewScrollViewHandler : ScrollViewHandler
{
	protected override MauiScrollView CreatePlatformView()
	{
		if (ScrollView != null && !ScrollView.ScrollingEnabled)
		{
			return base.CreatePlatformView();
		}
		nativeScrollView = new NativeListViewScrollView(new ContextThemeWrapper(base.MauiContext.Context, Style.scrollViewTheme), null, Attribute.scrollViewStyle);
```
Switching to IL view:
```
		// nativeScrollView = new NativeListViewScrollView(new ContextThemeWrapper(base.MauiContext.Context, Style.scrollViewTheme), null, Attribute.scrollViewStyle);
		IL_002b: nop
		IL_002c: ldarg.0
		IL_002d: ldarg.0
		IL_002e: call instance class [Microsoft.Maui]Microsoft.Maui.IMauiContext [Microsoft.Maui]Microsoft.Maui.Handlers.ElementHandler::get_MauiContext()
		IL_0033: callvirt instance class [Mono.Android]Android.Content.Context [Microsoft.Maui]Microsoft.Maui.IMauiContext::get_Context()
		IL_0038: ldsfld int32 [Microsoft.Maui]Microsoft.Maui.Resource/Style::scrollViewTheme
```

So, this is accessing a static field `Microsoft.Maui.Resource.Style.scrollViewTheme`. In .NET 8, we have a new feature in the Android that moves these values to be C# properties.

We have a linker step that is _supposed_ to go through and patch these up, but unfortunately it skips this assembly:

```
LinkAssembliesNoShrink
...
   Syncfusion.Maui.Core has no designer. 
```

Which is due to:

https://github.com/xamarin/xamarin-android/blob/94451e633e48c7204a86cbe7a0203649c9ecfbad/src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/LinkDesignerBase.cs#L45C46-L45C87

So, what happened is:

1. MAUI exposed its `Resource` class as a public API.
2. SyncFusion used it.
3. SyncFusion has no AndroidResource, etc. and no `[ResourceDesigner]`
4. The Android workload skipped processing this assembly.

FYI @dellis1972 

## Other question

Why does MAUI provide `Microsoft.Maui.Resource/Style::scrollViewTheme` as a public API in the first place?

**Comment by jonpryor** [comment]
Additionally, if we build for Android Release and get *more* diagnostic build output:

```
dotnet build -f net8.0-android -v:diag -p:Configuration=Release -p:_ExtraTrimmerArgs=--verbose > build.txt
```

then `build.txt` contains such wonderful log entries as:

```
                     ILLink:    Microsoft.Maui has no designer.
                     …
                     ILLink:    Syncfusion.Licensing has no designer.
                     ILLink:    Syncfusion.Maui.Core has no designer.
                     ILLink:    Syncfusion.Maui.DataSource has no designer.
                     ILLink:    Syncfusion.Maui.GridCommon has no designer.
                     ILLink:    Syncfusion.Maui.ListView has no designer.
```

Further validating that `Syncfusion.Maui.Core` is not being fixed up.

**Comment by jonpryor** [comment]
@dellis1972: `Microsoft.Maui.dll` is kinda/sorta a red herring (but not); it's illustrative of the scenario.  *Any* assembly could "cause" this scenario.

The scenario is as follows:

 1. In .NET 7, MAUI provided a public `Microsoft.Maui.Resources` type, which contains `@(AndroidResource)` derived types and fields.

 2. `Syncfusion.Maui.Core.dll` *references* `Microsoft.Maui.dll`, but does not itself contain `@(AndroidResource)` values. Consequently, it does not have an `[assembly: Android.Runtime.ResourceDesignerAttribute]` custom attribute.  (Nor does `Microsoft.Maui.dll`, for that matter!)

 3. `Syncfusion.Maui.Core.dll` uses fields from `Microsoft.Maui.Resources, Microsoft.Maui`.

 4. `Syncfusion.Maui.Core.dll` is *not* fixed up.

The result is that `Syncfusion.Maui.Core.dll` contains the IL statement:

```il
ldsfld int32 [Microsoft.Maui]Microsoft.Maui.Resource/Style::scrollViewTheme
```

which Does Not Exist™ in the current .NET 8 Android World Order.

@dellis1972 [asked](https://github.com/dotnet/maui/issues/17265#issuecomment-1758140155):

> 1. has maui not upgraded to ship a .net 8 assembly? If so why is it still using the old designer ?

MAUI *has* upgraded to ship a .NET 8 assembly.  However, `Syncfusion.Maui.Core.dll` is built against *.NET 7*, and thus is still using the *field-based* architecture.

> 2. The `Resource.designer.cs` class has been public for a while `public partial class Resource` as have the nested types. Not sure that was such a good idea given it could introduce all sorts of issues.

In retrospect, a bad idea. :-)

That's done, though; we can't change that.

> 3. I'm not entirely sure how to fix all of this without slowing down the build. We need to know which designer class is being used in order to fix up the code. If its using a class from an entirely seperate assembly that is gonna be a problem.

Could we do "two passes"?

First pass: what we do now.  Track all assemblies which are updated.

Second pass: Review all assemblies which (1) reference assemblies which were updated in the first pass, and(/or?) (2) have *type references* to `*Resource` types.  Fix up *those* assemblies.

(Add fixed up assemblies to assemblies from 1st pass, repeat second pass ad-infinitum, until all assemblies are hit?)

I think the "key" optimization idea is that we don't necessarily need to "fixup" *everything*; we "only" need to key off of assemblies which either contain `*.Resource` types (and have `[assembly: Android.Runtime.ResourceDesignerAttribute]`) *or reference* `*.Resource` types, *and* the referenced `*.Resource` type is a "Resource" type (in an assembly with `[assembly: Android.Runtime.ResourceDesignerAttribute]`, etc.).

This will hopefully significantly narrow down the number of assemblies that we need to process (from "everything").

**Comment by jonpryor** [comment]
Another interesting shell pipeline I created while debugging this:

```sh
dotnet tool install --global dotnet-ilverify
# creates $HOME/.dotnet/tools/ilverify

cd obj/Release/net8.0-android/android-arm/linked

for f in *.dll ; do \
    echo "## $f"; \
    $HOME/.dotnet/tools/ilverify $f --tokens --system-module System.Private.CoreLib $(ls -1 *.dll | grep -v $f | sed -E 's/^/-r /g') ; \
done > ilverify-errors.txt
```

The resulting `ilverify-errors.txt` contains all IL verification errors for all assemblies in the current working directory.  It has many things which can be ignored (it doesn't like `unsafe` code), but in the context of Syncfusion it finds:

```
## Syncfusion.Maui.Core.dll
[IL]: Error [ClassLoadGeneral]: […/SfListViewBug/obj/Release/net8.0-android/android-arm/linked/Syncfusion.Maui.Core.dll : Syncfusion.Maui.Core.Internals.ListViewScrollViewHandler::CreatePlatformView()] Failed to load type 'Style' from assembly 'Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
[IL]: Error [ClassLoadGeneral]: […/SfListViewBug/obj/Release/net8.0-android/android-arm/linked/Syncfusion.Maui.Core.dll : Syncfusion.Maui.Core.Hosting.DataGridScrollViewHandler::CreatePlatformView()] Failed to load type 'Style' from assembly 'Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
2 Error(s) Verifying …/SfListViewBug/obj/Release/net8.0-android/android-arm/linked/Syncfusion.Maui.Core.dll
```

**Comment by dellis1972** [comment]
I updated PR https://github.com/xamarin/monodroid/pull/1375 it should work now.

**Comment by jonpryor** [comment]
@dellis1972: I think you commented on the wrong issue?  xamarin/monodroid#1375 is unrelated.

**Comment by dellis1972** [comment]
doh

**Comment by dellis1972** [comment]
IT should be https://github.com/xamarin/xamarin-android/pull/8416

**Comment by michaelonz** [comment]
I am having the same issue in RC2

**Comment by jonathanpeppers** [comment]
@michaelonz can you try `AndroidUseDesignerAssembly=false` in the meantime?

https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/building-apps/build-properties.md#androidusedesignerassembly

**Comment by michaelonz** [comment]
Hi @jonathanpeppers 
i tried AndroidUseDesignerAssembly but got the following compile error instead:

2>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-rc.2.468\tools\Xamarin.Android.Resource.Designer.targets(146,3): error XA1034: Your project references 'C:\Users\michaelo\.nuget\packages\inputkit.maui\4.4.0-pre.1\lib\net8.0-android34.0\InputKit.Maui.dll' which uses the `_Microsoft.Android.Resource.Designer` assembly, but you do not have this feature enabled. Please set the `AndroidUseDesignerAssembly` MSBuild property to `true` in your project file.

So at this stage with rc2 I cannot run with maui on android until a patch is released - I can run on IOS.

**Comment by dellis1972** [comment]
@michaelonz  ah, yup if a nuget is already using the new Resource Designer assembly there isn't much we can do. 
The fix has been merged though so thats a good thing :)

**Comment by TedMobile** [comment]
Great to see this has been fixed!!! I am affected too and wondering if there is a night build we can use to test this and that will allow us  to carry on our migration to .net8
thanks

**Comment by michaelonz** [comment]
So when you say it’s merged - is this a visual studio issue? or what component do we need to watch for an update to get this change?

**Comment by Zack-G-I-T** [comment]
@jonathanpeppers hi, i tried using syncfusion version 41 on maui prerelease from the nightly build and I am still getting the same error as before

**Comment by dellis1972** [comment]
The fix will be in the android workload. I'm not sure if the maui prerelease will include that, as it will depend on maui bumping the verison of android its dependent on I think.

**Comment by Zack-G-I-T** [comment]
@dellis1972 hi so are you saying on .NEt 8 GA this should be fixed?

**Comment by dellis1972** [comment]
It should be fixed in RC 2.1 but that has not shipped yet.

**Comment by marcberman14** [comment]
Any idea when RC 2.1 will be released? I see it isn't part of the releases yet.

**Comment by jonathanpeppers** [comment]
There are usually no public release dates for Visual Studio or .NET.

Usually, .NET 8 GA ships the same day as [.NET conf](https://www.dotnetconf.net/), though.

**Comment by jonathanpeppers** [comment]
This is released now:
* https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview#1780-pre60--visual-studio-2022-version-178-preview-6
* https://github.com/xamarin/xamarin-android/releases/tag/34.0.0-rc.2.479

**Comment by michaelonz** [comment]
Hi @jonathanpeppers  - i would like to report back that i have tested this new release and it has resolved the issue - thanks everyone for the effort on this as it was a show stopper :)

**Comment by hansmbakker** [comment]
> It should be fixed in RC 2.1 but that has not shipped yet.

@dellis1972 seeing that Visual Studio 17.8 preview 6 is released and that it fixed this issue for people, does that mean that mean that dotnet 8 rc2.1 is also released?

After updating Visual Studio to 17.8 preview 6, it seems that only the Apple workloads are rc2.1:

> `dotnet sdk check`
```
.NET SDKs:
Version                   Status
-------------------------------------
8.0.100-rc.2.23502.2      Up to date.

.NET Runtimes:
Name                              Version                  Status
----------------------------------------------------------------------
Microsoft.NETCore.App             8.0.0-rc.2.23479.6       Up to date.
Microsoft.WindowsDesktop.App      8.0.0-rc.2.23479.10      Up to date.
Microsoft.AspNetCore.App          8.0.0-rc.2.23480.2       Up to date.
```

> `dotnet workload list`
```
Installed Workload Id      Manifest Version                       Installation Source
-------------------------------------------------------------------------------------
maui-windows               8.0.0-rc.2.9511/8.0.100-rc.2           VS 17.8.34227.203
maccatalyst                17.0.8465-net8-rc2.1/8.0.100-rc.2      VS 17.8.34227.203
ios                        17.0.8465-net8-rc2.1/8.0.100-rc.2      VS 17.8.34227.203
android                    34.0.0-rc.2.479/8.0.100-rc.2           VS 17.8.34227.203
```

**Comment by hansmbakker** [comment]
Nvm, according to https://github.com/xamarin/xamarin-android/releases/tag/34.0.0-rc.2.479 it is correct, it is just confusing that rc2.1 this is not reflected in the manifest versioning for android.
