### ISSUE TITLE
Can't "Pair to Mac" with Visual Studio 17.9.3

### ISSUE THREAD

**Issue by marco-skizza** [dotnet/maui#21174]
### Description

Hi

After installing Visual Studio 17.9.3 I can't pair to my Mac anymore.
I get the following error:
```
Could not install workload 'ios'. Details: Unhandled exception: Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestCompositionException: Die Workload ???ios???, die von der Workload ???maui-ios??? im Manifest ???microsoft.net.sdk.maui??? [/Users/marco/Library/Caches/Xamarin/XMA/SDKs/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maui/8.0.3/WorkloadManifest.json] erweitert wurde, konnte nicht gefunden werden.
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.<>c__DisplayClass26_0.<<EnumerateWorkloadWithExtends>g__EnumerateWorkloadWithExtendsRec|0>d.MoveNext()
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.<>c__DisplayClass26_0.<<EnumerateWorkloadWithExtends>g__EnumerateWorkloadWithExtendsRec|0>d.MoveNext()
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.<>c__DisplayClass26_0.<<EnumerateWorkloadWithExtends>g__EnumerateWorkloadWithExtendsRec|0>d.MoveNext()
   at System.Linq.Enumerable.AppendPrependIterator`1.LoadFromEnumerator()
   at System.Linq.Enumerable.AppendPrepend1Iterator`1.MoveNext()
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
```

Maybe there is some wrong .NET version referenced somewhere?
Because I think we have .NET `8.0.202` now and not `8.0.100` as seen in the error.
Maybe a similar issue we had with the previous update of Visual Studio...?

I deleted the following folder on my Mac, but that didn't help either:
```
~/Library/Caches/Xamarin/XMA/SDKs/dotnet
```

### Steps to Reproduce

- Install Visual Studio 17.9.3
- Try to "Pair to Mac"

### Link to public reproduction project repository

-

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

Visual Studio 17.9.3

### Did you find any workaround?

No

**Comment by jaosnz-rep** [comment]
Can repro on 17.9.3, this is a known bug https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1977607.

**Comment by jfversluis** [comment]
This should be fixed in an upcoming update for Visual Studio. In the meanwhile you can use the workaround provided here.

For (potential) issues with Visual Studio please report it through the Visual Studio Help menu, then Provide Feedback and Report a Problem. That will route it to the appropriate team directly. Thanks!

**Comment by TonyLugg** [comment]
I'm having this issue too.  How can something so fundamental slip through the update cracks?

**Comment by jaosnz-rep** [comment]
> @jaosnz-rep I can't get to the link, it says I don't have access or the url is wrong. Where are the files on Windows that have to be copied?
If you installed according to the default path, it will be in the following path:
C:\Program Files\dotnet\sdk-manifests
![image](https://github.com/dotnet/maui/assets/82628041/99b09a25-cfe8-4b6e-8a0a-10b114f0c1dc)

**Comment by TonyLugg** [comment]
> > @jaosnz-rep I can't get to the link, it says I don't have access or the url is wrong. Where are the files on Windows that have to be copied?
> > If you installed according to the default path, it will be in the following path:
> > C:\Program Files\dotnet\sdk-manifests
> > ![image](https://private-user-images.githubusercontent.com/82628041/314395930-99b09a25-cfe8-4b6e-8a0a-10b114f0c1dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MzU4MDIsIm5iZiI6MTcxMDkzNTUwMiwicGF0aCI6Ii84MjYyODA0MS8zMTQzOTU5MzAtOTliMDlhMjUtY2ZlOC00YjZlLThhMGEtMTBiMTE0ZjBjMWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDExNTE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhYzVmOGFkMzIwOGNhZjljNmQ1ZjFiMWQ5NzlmOTEyNjk0MTkwNTI2N2VhZjg1MjJhNjcyNjEwMGYwZDZhZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aLYcGPxa-5yJJlSYudgWUH_EgtHYN3f24KyGcVyVjqY)

Yeah, thanks, I found the answer at https://github.com/dotnet/maui/issues/20686#issuecomment-1971523760

**Comment by marco-skizza** [comment]
P.S.: Still seems to be an issue with Visual Studio 17.9.4

**Comment by techmanDAV** [comment]
I am having the  same issue.  I went from ver 17.9 to 17.9.4 and I can no longer pair to the mac.  I made sure all the computers and IDEs were upted and I still got the rror message.

**Comment by raconn** [comment]
Using 17.9.4. I had to update the workloads on both machines. 

Ran "sudo dotnet workload update" from Mac terminal and "dotnet workload update" on Windows 10 PowerShell. After updating for about 10 minutes completed, I was able to successfully pair from VS 2022.

**Comment by Pughgramming** [comment]
17.9.5 has dropped. Do we know if this has solved the issue?

**Comment by Ni2Be** [comment]
@jfversluis With which release will this be fixed / where is it tracked?

**Comment by jfversluis** [comment]
Unfortunately I can't comment on specific releases and timelines in this case.

According to this it should be fixed in VS 17.10 Preview 2: https://developercommunity.visualstudio.com/t/Unable-to-install-MAUI-workload-on-Mac-u/10595252#T-N10604031

Also see: https://github.com/dotnet/maui/issues/20686

If you still experience this please upvote and/or leave your comments on that feedback ticket.

**Comment by mauroa** [comment]
Hi everyone. 
The fix for 17.9 should be shipped in the next Service Release. For 17.10, it's already available in the latest preview. In the meantime, you can apply the workaround mentioned in these two tickets below, and let me know if you have any problem:

https://developercommunity.visualstudio.com/t/After-upgrading-to-Visual-Studio-2002-v1/10615131

https://developercommunity.visualstudio.com/t/Issue-pairing-to-mac-with-latest-version/10565611

Thanks for your patience with this.

**Comment by s3ttingQ** [comment]
Hello, I am still having some troubles. On my windows i have VS 17.9.4 and when i try to connect to a mac remotely i get the missing workloads message about net.sdk.maui/8.0.3 but my windows folder is 8.0.7. Some advice will be appreciated !

**Comment by marco-skizza** [comment]
@s3ttingQ

I just copied the following folder from Windows:
`C:\Program Files\dotnet\sdk-manifests`

...and replaced the same folder on the Mac in:
`~/Library/Caches/Xamarin/XMA/SDKs/dotnet`

**Comment by techmanDAV** [comment]
Hello,
I am having the same issue with the same error. I get this error with 17.9.4 and 17.9.5.  The only workaround I know for now is to rollback to 17.9.0. Also, I briefly read the release notes and I did not find any reference to a fix to the problem.

**Comment by scriptBoris** [comment]
This is still a problem in 17.9.5

**Comment by marco-skizza** [comment]
Seems to be fixed in Visual Studio `17.9.6`

**Comment by jminack** [comment]
Fixed for me as well for Visual Studio 17.9.6.
