### ISSUE TITLE
[Bug] CarouselView not rendering in Android after VS2022 Preview 3 update

### ISSUE THREAD

**Issue by PaulAnderson02** [dotnet/maui#2118]
### Description
CarouselView not rendering in Android after VS2022 Preview 3 update when using ItemTemplate.

### Steps to Reproduce

1. Add a simple CarouselView to the sample.
2. Assign a simple collection.
3. Add a label to the Itemtemplate of Carousel

### Expected Behavior
CarouselView should render the label.

### Actual Behavior
UI freezed with .Net SplashScreen.

### Basic Information

- Version with issue: 6.0.100-preview.7.1345
- Last known good version: 6.0.100-preview.6.xxx
- IDE: VS 2022

### Screenshots

![Screenshot_1629113723](https://user-images.githubusercontent.com/42271912/129557569-73390e58-01b9-4c1c-92a8-2d6fcbe72f76.png)

### Code
```
<CarouselView x:Name="carousel">
    <CarouselView.ItemTemplate>
        <DataTemplate>
            <Label Text="Carousel 1" />
        </DataTemplate>
    </CarouselView.ItemTemplate>
</CarouselView>
```
```
public MainPage1()
{
    InitializeComponent();
    ObservableCollection<string> itemCollection = new ObservableCollection<string>();
    itemCollection.Add("Test 1");
    itemCollection.Add("Test 2");
    itemCollection.Add("Test 3");
    itemCollection.Add("Test 4");
    itemCollection.Add("Test 5");
    this.carousel.ItemsSource = itemCollection;
}
```

### Reproduction Link

[MauiApp9.zip](https://github.com/dotnet/maui/files/6992037/MauiApp9.zip)

**Comment by PaulAnderson02** [comment]
Getting continuous logs in output as below

[nyname.MauiApp] Explicit concurrent copying GC freed 14659(1162KB) AllocSpace objects, 1(64KB) LOS objects, 40% free, 35MB/59MB, paused 417us total 133.239ms
[nyname.MauiApp] Explicit concurrent copying GC freed 14650(1142KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 36MB/60MB, paused 414us total 135.201ms
[nyname.MauiApp] Explicit concurrent copying GC freed 14650(1174KB) AllocSpace objects, 0(0B) LOS objects, 38% free, 37MB/61MB, paused 421us total 183.855ms
[nyname.MauiApp] Explicit concurrent copying GC freed 14705(1212KB) AllocSpace objects, 0(0B) LOS objects, 38% free, 38MB/62MB, paused 416us total 139.772ms
[nyname.MauiApp] Explicit concurrent copying GC freed 14659(1194KB) AllocSpace objects, 0(0B) LOS objects, 37% free, 39MB/63MB, paused 427us total 143.765ms
[nyname.MauiApp] Explicit concurrent copying GC freed 14652(1336KB) AllocSpace objects, 0(0B) LOS objects, 37% free, 40MB/64MB, paused 431us total 153.412ms
[nyname.MauiApp] Explicit concurrent copying GC freed 14650(1259KB) AllocSpace objects, 0(0B) LOS objects, 36% free, 41MB/65MB, paused 419us total 151.644ms
[nyname.MauiApp] Explicit concurrent copying GC freed 14650(1289KB) AllocSpace objects, 0(0B) LOS objects, 36% free, 42MB/66MB, paused 461us total 155.129ms
[nyname.MauiApp] Explicit concurrent copying GC freed 14705(1350KB) AllocSpace objects, 0(0B) LOS objects, 35% free, 43MB/67MB, paused 424us total 159.030ms
[nyname.MauiApp] Explicit concurrent copying GC freed 14659(1320KB) AllocSpace objects, 0(0B) LOS objects, 35% free, 44MB/68MB, paused 423us total 166.907ms
[nyname.MauiApp] Explicit concurrent copying GC freed 14650(1335KB) AllocSpace objects, 0(0B) LOS objects, 34% free, 45MB/69MB, paused 417us total 165.008ms
[nyname.MauiApp] Explicit concurrent copying GC freed 14651(1402KB) AllocSpace objects, 0(0B) LOS objects, 34% free, 46MB/70MB, paused 419us total 166.774ms
[nyname.MauiApp] Explicit concurrent copying GC freed 14705(1366KB) AllocSpace objects, 0(0B) LOS objects, 33% free, 46MB/70MB, paused 422us total 171.409ms
[nyname.MauiApp] Explicit concurrent copying GC freed 14658(1397KB) AllocSpace objects, 0(0B) LOS objects, 33% free, 47MB/71MB, paused 432us total 177.287ms
[nyname.MauiApp] WaitForGcToComplete blocked HeapTrim on HeapTrim for 110.082ms
[nyname.MauiApp] Explicit concurrent copying GC freed 14651(1450KB) AllocSpace objects, 0(0B) LOS objects, 32% free, 48MB/72MB, paused 902us total 199.680ms
[nyname.MauiApp] Explicit concurrent copying GC freed 14650(1411KB) AllocSpace objects, 0(0B) LOS objects, 32% free, 49MB/73MB, paused 416us total 191.758ms
[nyname.MauiApp] Explicit concurrent copying GC freed 14704(1438KB) AllocSpace objects, 0(0B) LOS objects, 32% free, 50MB/74MB, paused 417us total 193.841ms
[nyname.MauiApp] Explicit concurrent copying GC freed 2320(138KB) AllocSpace objects, 0(0B) LOS objects, 32% free, 50MB/74MB, paused 420us total 216.457ms
[nyname.MauiApp] Explicit concurrent copying GC freed 69(18KB) AllocSpace objects, 0(0B) LOS objects, 32% free, 50MB/74MB, paused 416us total 184.819ms
[nyname.MauiApp] Explicit concurrent copying GC freed 12794(1488KB) AllocSpace objects, 0(0B) LOS objects, 31% free, 51MB/75MB, paused 618us total 193.298ms
[nyname.MauiApp] Explicit concurrent copying GC freed 14651(1533KB) AllocSpace objects, 0(0B) LOS objects, 31% free, 52MB/76MB, paused 551us total 196.968ms
[nyname.MauiApp] Explicit concurrent copying GC freed 14650(1462KB) AllocSpace objects, 0(0B) LOS objects, 30% free, 53MB/77MB, paused 415us total 199.336ms
[nyname.MauiApp] Explicit concurrent copying GC freed 14650(1498KB) AllocSpace objects, 0(0B) LOS objects, 30% free, 54MB/78MB, paused 417us total 202.025ms
[nyname.MauiApp] Explicit concurrent copying GC freed 14706(1577KB) AllocSpace objects, 0(0B) LOS objects, 30% free, 55MB/79MB, paused 417us total 209.241ms
[nyname.MauiApp] Explicit concurrent copying GC freed 14658(1498KB) AllocSpace objects, 0(0B) LOS objects, 29% free, 56MB/80MB, paused 428us total 227.585ms
[nyname.MauiApp] Explicit concurrent copying GC freed 14651(1570KB) AllocSpace objects, 0(0B) LOS objects, 29% free, 57MB/81MB, paused 426us total 219.559ms
[nyname.MauiApp] Explicit concurrent copying GC freed 14650(1526KB) AllocSpace objects, 0(0B) LOS objects, 29% free, 58MB/82MB, paused 417us total 220.870ms
[nyname.MauiApp] Explicit concurrent copying GC freed 14706(1604KB) AllocSpace objects, 0(0B) LOS objects, 28% free, 59MB/83MB, paused 919us total 228.809ms
[nyname.MauiApp] Explicit concurrent copying GC freed 14659(1618KB) AllocSpace objects, 0(0B) LOS objects, 28% free, 60MB/84MB, paused 420us total 229.887ms
[nyname.MauiApp] Explicit concurrent copying GC freed 14650(1597KB) AllocSpace objects, 0(0B) LOS objects, 28% free, 61MB/85MB, paused 421us total 232.983ms
[nyname.MauiApp] Explicit concurrent copying GC freed 14650(1604KB) AllocSpace objects, 0(0B) LOS objects, 27% free, 61MB/85MB, paused 428us total 247.442ms
[nyname.MauiApp] Explicit concurrent copying GC freed 14705(1675KB) AllocSpace objects, 0(0B) LOS objects, 27% free, 62MB/86MB, paused 417us total 251.689ms
Loaded assembly: /data/data/com.companyname.MauiApp7/files/.__override__/System.Console.dll [External]
[monodroid] MonodroidRuntime::monodroid_pinvoke_override ("liblog", "__android_log_print")
[monodroid] MonodroidRuntime::monodroid_dlopen ("liblog", 0x2, 0x0, 0x0)
[monodroid-assembly] Shared library 'liblog' not loaded, p/invoke '__android_log_print' may fail
[monodroid-gc] 46080 outstanding GREFs. Performing a full GC!
[nyname.MauiApp] Explicit concurrent copying GC freed 12521(1389KB) AllocSpace objects, 0(0B) LOS objects, 27% free, 63MB/87MB, paused 620us total 233.083ms
[monodroid-gc] 46080 outstanding GREFs. Performing a full GC!
[nyname.MauiApp] Explicit concurrent copying GC freed 1591(78KB) AllocSpace objects, 0(0B) LOS objects, 27% free, 63MB/87MB, paused 417us total 243.120ms
[monodroid-gc] 46081 outstanding GREFs. Performing a full GC!
[nyname.MauiApp] Explicit concurrent copying GC freed 13(31KB) AllocSpace objects, 0(0B) LOS objects, 27% free, 63MB/87MB, paused 425us total 244.048ms
[monodroid-gc] 46082 outstanding GREFs. Performing a full GC!
[nyname.MauiApp] Explicit concurrent copying GC freed 4(31KB) AllocSpace objects, 0(0B) LOS objects, 27% free, 63MB/87MB, paused 418us total 232.289ms
[monodroid-gc] 46083 outstanding GREFs. Performing a full GC!
[nyname.MauiApp] Explicit concurrent copying GC freed 23(31KB) AllocSpace objects, 0(0B) LOS objects, 27% free, 63MB/87MB, paused 481us total 245.929ms
[nyname.MauiApp] WaitForGcToComplete blocked HeapTrim on HeapTrim for 124.576ms
[monodroid-gc] 46083 outstanding GREFs. Performing a full GC!
[nyname.MauiApp] Explicit concurrent copying GC freed 47(29KB) AllocSpace objects, 0(0B) LOS objects, 27% free, 63MB/87MB, paused 419us total 239.696ms
[monodroid-gc] 46084 outstanding GREFs. Performing a full GC!
[nyname.MauiApp] Explicit concurrent copying GC freed 13(31KB) AllocSpace objects, 0(0B) LOS objects, 27% free, 63MB/87MB, paused 563us total 242.575ms
[monodroid-gc] 46085 outstanding GREFs. Performing a full GC!
[nyname.MauiApp] Explicit concurrent copying GC freed 4(31KB) AllocSpace objects, 0(0B) LOS objects, 27% free, 63MB/87MB, paused 432us total 238.427ms
[monodroid-gc] 46086 outstanding GREFs. Performing a full GC!
[nyname.MauiApp] Explicit concurrent copying GC freed 23(31KB) AllocSpace objects, 0(0B) LOS objects, 27% free, 63MB/87MB, paused 533us total 241.405ms

**Comment by PaulAnderson02** [comment]
If I commented out the DataTemplate in the above code and provide a List<string> as collection, I'm getting an infinite loop of items populated.

![Screenshot_1629178756](https://user-images.githubusercontent.com/42271912/129669774-f8f3cbc5-eb31-458e-81ea-5da9196b1317.png)

**Comment by PaulAnderson02** [comment]
Any update on this issue?

**Comment by PaulAnderson02** [comment]
@davidortinau Will this be considered as it is a major break with preview 3 version

**Comment by PaulAnderson02** [comment]
Any update on this issue?

**Comment by hartez** [comment]
I believe this is the same issue as #1882

**Comment by PaulAnderson02** [comment]
@hartez  Any update on this issue?

**Comment by shimingsg** [comment]
Verified Repro with Android 11. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/EeAllE3EzMdPqkUWsP5r2H4B_m78VIq9nHxmUoyrui6ceQ?e=y2v0I4

**Comment by shimingsg** [comment]
Verified Repro with Android 11. Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/EeAllE3EzMdPqkUWsP5r2H4B_m78VIq9nHxmUoyrui6ceQ?e=6KqeSa

**Comment by Redth** [comment]
This should be fixed in preview 14 or RC1. Please open a new issue if this is not the case.

**Comment by Mephisztoe** [comment]
As far as I can tell, I am on Preview 14 and this issue still persists. However, "This should be fixed in preview 14 or RC1" is not very specific though. It might be fixed in RC1 after all... which is not rolled out yet.

**Comment by Redth** [comment]
Apologies for the ambiguity.  I thought it was perhaps fixed by a change in Preview 14 which appears not to be the case, however it will be fixed in the upcoming RC1 release as I just verified from our main branch now:

![2022-03-29_10-39-46](https://user-images.githubusercontent.com/271950/160637547-3b31002a-3db0-455f-bbca-cdeaed6b3f96.gif)
