### ISSUE TITLE
Span TapGesture on Label FormattedString

### ISSUE THREAD

**Issue by jshaffermanLT** [dotnet/maui#21284]
### Description

I have followed the MAUI docs and when I try to run our application (NET 8 MAUI) it works fine on Android but the command is never executed on iOS. 

This is the class verbatim from the MAUI docs:
```C#
public class HyperlinkSpan : Span
{
    public static readonly BindableProperty UrlProperty =
        BindableProperty.Create(nameof(Url), typeof(string), typeof(HyperlinkSpan), null);

    public string Url
    {
        get { return (string)GetValue(UrlProperty); }
        set { SetValue(UrlProperty, value); }
    }

    public HyperlinkSpan()
    {
        TextDecorations = TextDecorations.Underline;
        TextColor = Colors.Blue;
        GestureRecognizers.Add(new TapGestureRecognizer
        {
            // Launcher.OpenAsync is provided by Essentials.
            Command = new Command(async () => await Launcher.OpenAsync(Url))
        });
    }
}
```

This is the usage verbatim from the docs:

```XAML
<Label>
            <Label.FormattedText>
                <FormattedString>
                    <Span Text="Alternatively, click " />
                    <local:HyperlinkSpan Text="here"
                                         Url="https://learn.microsoft.com/dotnet/" />
                    <Span Text=" to view .NET documentation." />
                </FormattedString>
            </Label.FormattedText>
        </Label>
```

The command is simply never executed on iOS. It works fine on Android.

Using the MAUI docs from here: https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/label?view=net-maui-8.0#use-formatted-text

### Steps to Reproduce

1. Create a MAUI NET 8 project
2. Create a MAUI page
3. Place content of page as the Label (in the description)
4. Run on Android (works fine)
5. Run on iOS and command is never executed

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

I have not been able to find a workaround. I tried to use the Tapped event instead of the command but it has the sam affect (no event propagated on iOS)

**Comment by jfversluis** [comment]
I think this should be fixed with the release from last week. Can you confirm that you are using this version? 

https://github.com/dotnet/maui/releases/tag/8.0.10

**Comment by jshaffermanLT** [comment]
@jfversluis I am still not seeing it work with the latest update from NET 8. I went to this link:
 
https://dotnet.microsoft.com/en-us/download which appears to be 8.0.3 (latest suggested). 

I then updated my workloads using dotnet workload update and I checked with botnet workloads list and this is what I am seeing:

Installed Workload Id      Manifest Version      Installation Source
--------------------------------------------------------------------
maui                       8.0.7/8.0.100         SDK 8.0.200  

I am slightly confused because I would have expected to see SDK 8.203 but it does appear to be on 8.0.10

**Comment by flipper09112** [comment]
@jfversluis occours in 8.0.10 version too

**Comment by PureWeen** [comment]
> @jfversluis occours in 8.0.10 version too

Are you testing the sample from the docs? or do you have an additional repro you can add?

**Comment by jshaffermanLT** [comment]
@PureWeen I am using the example straight from the docs

**Comment by jshaffermanLT** [comment]
@PureWeen I know it wasn't directed at me but I am using the sample from the docs

**Comment by PureWeen** [comment]
I tested that sample against 8.0.10 and it worked for me

Can you please zip up your sample?

**Comment by jshaffermanLT** [comment]
@PureWeen Here is the sample project I just ran and saw that iOS doesn't respond when tapped but Android build does. I am using Rider (2023.3.4), running it on an iOS simulator (iPhone 15), and using Xcode 15.2. I did a normal scaffolded project but can't attach the sample because it's too big so I will put the code in-line here (there is only one page so this is it)

`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:SpanMauiTest"
             x:Class="SpanMauiTest.MainPage"
             x:DataType="local:MainPage">
    <ScrollView>
        <VerticalStackLayout
            Padding="30,0"
            Spacing="25">
            <Image
                Source="dotnet_bot.png"
                HeightRequest="185"
                Aspect="AspectFit"
                SemanticProperties.Description="dot net bot in a race car number eight" />

            <Label
                Text="Hello, World!"
                Style="{StaticResource Headline}"
                SemanticProperties.HeadingLevel="Level1" />

            <Label
                Text="Welcome to &#10;.NET Multi-platform App UI"
                Style="{StaticResource SubHeadline}"
                SemanticProperties.HeadingLevel="Level2"
                SemanticProperties.Description="Welcome to dot net Multi platform App U I" />

            <Label>
                <Label.FormattedText>
                    <FormattedString>
                        <Span Text="Alternatively, click " />
                        <Span Text="here"
                              TextColor="Blue"
                              TextDecorations="Underline">
                            <Span.GestureRecognizers>
                                <TapGestureRecognizer Command="{Binding TapCommand}"
                                                      CommandParameter="https://learn.microsoft.com/dotnet/maui/" />
                            </Span.GestureRecognizers>
                        </Span>
                        <Span Text=" to view .NET MAUI documentation." />
                    </FormattedString>
                </Label.FormattedText>
            </Label>
            
            <Button
                x:Name="CounterBtn"
                Text="Click me" 
                SemanticProperties.Hint="Counts the number of times you click"
                Clicked="OnCounterClicked"
                HorizontalOptions="Fill" />
        </VerticalStackLayout>
    </ScrollView>

</ContentPage>
`

Code behind:

`using System.Windows.Input;

namespace SpanMauiTest;

public partial class MainPage : ContentPage
{
    public ICommand TapCommand => new Command<string>(async (url) => await Launcher.OpenAsync(url));

    int count = 0;

    public MainPage()
    {
        InitializeComponent();

        BindingContext = this;
    }

    private void OnCounterClicked(object sender, EventArgs e)
    {
        count++;

        if (count == 1)
            CounterBtn.Text = $"Clicked {count} time";
        else
            CounterBtn.Text = $"Clicked {count} times";

        SemanticScreenReader.Announce(CounterBtn.Text);
    }
}`

If you need anything else from me, please let me know and I will get it to you ASAP

**Comment by PureWeen** [comment]
@jshaffermanLT if you delete the bin/obj folders or push it to github then we can make sure we're testing the same thing.

**Comment by jshaffermanLT** [comment]
[SpanMauiTest.zip](https://github.com/dotnet/maui/files/14728648/SpanMauiTest.zip)

Here is the sample app I am using

**Comment by QianaJiao** [comment]
Verified this issue with Visual Studio 17.10.0 Preview 2 (8.0.14/8.0.7). It repro on iOS platform with 8.0.7, and not repro on 8.0.14.

**Comment by jfversluis** [comment]
@jshaffermanLT if I pull down your sample and change the NuGet version to 8.0.14, which is the latest release, your sample works for me.

![image](https://github.com/dotnet/maui/assets/939291/da635ef9-abee-4f97-b4cb-6ed1eb100936)

Could you confirm that this is the case for you as well? If so, please close this one, thanks!

**Comment by jfversluis** [comment]
Perfect, thanks for letting us know!
