### ISSUE TITLE
[8.0.10] Windows FontImageSourceService assumes MSIX packaging

### ISSUE THREAD

**Issue by AndreasReitberger** [dotnet/maui#21333]
### Description

Reopened #15802 @mattleibow 
Ref: https://github.com/dotnet/maui/issues/15802

The issue is still there in `8.0.10` and `1.2.0` (WinUI).

![image](https://github.com/dotnet/maui/assets/2952443/2c0d93d6-17ff-4018-a92f-4b52df365337)

### Steps to Reproduce

See: https://github.com/dotnet/maui/issues/15802#issuecomment-2009325140

### Link to public reproduction project repository

https://github.com/dotnet/maui/issues/15802

### Version with bug

8.0.10 SR3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

**Comment by mattleibow** [comment]
Until we release SR4, you also need to update Win2D. This was a 2 part fix in MAUI and in Win2D. We fixed our part, but had to wait for Win2D to release. They did that, now we updated MAUI to use the new Win2D.

**Comment by AndreasReitberger** [comment]
Thanks for the update. That's why I updated the `Win2D` part manually.

```xaml
 <!-- Windows specifics-->
  <ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">
    <PackageReference Include="Microsoft.Graphics.Win2D" Version="1.2.0" />
  </ItemGroup>
```

But this still doesn't work. Or did I miss something? 
Thank you :)

**Comment by BurkusCat** [comment]
I posted a comment in the original thread (https://github.com/dotnet/maui/issues/15802#issuecomment-1995905743). Updating to MAUI SR3 + Microsoft.Graphics.Win2D 1.2.0 doesn't appear to resolve the issue.

**Comment by jaosnz-rep** [comment]
Can repro this issue on MAUI 8.0.10 and Microsoft.Graphics.Win2D 1.2.0 with the sample project in the steps.

**Comment by jeremy-visionaid** [comment]
@AndreasReitberger This works OK for me with MAUI 8.0.14 and Win2D 1.2.0:

```
	<PropertyGroup>
		<WindowsPackageType>None</WindowsPackageType>
		<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />
		<PackageReference Include="Microsoft.Graphics.Win2D" Version="1.2.0" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.14" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.14" />
	</ItemGroup>
```

**Comment by AndreasReitberger** [comment]
@jeremy-visionaid 
Thanks for that example.
If I apply your setttings, the application crashes on startup. Also I needed to set the `launchSettings` to `Project` to start the app. Is this correct?

This is what I get as error output:

> Microsoft.Maui.FontRegistrar: Warning: Unable to load font 'MontserratMedium'.
> 
> System.InvalidOperationException: Operation is not valid due to the current state of the object.
>    at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
>    at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
>    at ABI.Windows.Storage.IApplicationDataStaticsMethods.get_Current(IObjectReference _obj)
>    at Windows.Storage.ApplicationData.get_Current()
>    at Microsoft.Maui.EmbeddedFontLoader.LoadFont(EmbeddedFont font)
>    at Microsoft.Maui.FontRegistrar.LoadEmbeddedFont(String cacheKey, String filename, String alias, Stream stream)
>    at Microsoft.Maui.FontRegistrar.GetFont(String font)
> 'ActiveDirectorySearch.exe' (CoreCLR: clrhost): Loaded 'C:\Users\q36606\Documents\GitHub\ActiveDirectorySearchMaui\src\ActiveDirectorySearch\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\Microsoft.Graphics.Canvas.Interop.dll'. 
> Exception thrown: 'System.InvalidOperationException' in System.Private.Uri.dll
> Microsoft.Maui.FontManager: Error: Error loading font 'Assets/Fonts/MontserratMedium.ttf'.
> 
> System.InvalidOperationException: This operation is not supported for a relative URI.
>    at System.Uri.get_AbsolutePath()
>    at Microsoft.Maui.FontManager.FindFontFamilyName(String fontFile)
> Exception thrown: 'System.InvalidOperationException' in System.Private.Uri.dll
> Microsoft.Maui.FontManager: Error: Error loading font 'Assets/Fonts/MontserratMedium.otf'.
> 
> System.InvalidOperationException: This operation is not supported for a relative URI.
>    at System.Uri.get_AbsolutePath()
>    at Microsoft.Maui.FontManager.FindFontFamilyName(String fontFile)
> Exception thrown: 'System.InvalidOperationException' in WinRT.Runtime.dll
> Microsoft.Maui.FontRegistrar: Warning: Unable to load font 'MontserratSemiBold'.
> 
> System.InvalidOperationException: Operation is not valid due to the current state of the object.
>    at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
>    at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
>    at ABI.Windows.Storage.IApplicationDataStaticsMethods.get_Current(IObjectReference _obj)
>    at Windows.Storage.ApplicationData.get_Current()
>    at Microsoft.Maui.EmbeddedFontLoader.LoadFont(EmbeddedFont font)
>    at Microsoft.Maui.FontRegistrar.LoadEmbeddedFont(String cacheKey, String filename, String alias, Stream stream)
>    at Microsoft.Maui.FontRegistrar.GetFont(String font)
> Exception thrown: 'System.InvalidOperationException' in System.Private.Uri.dll
> Microsoft.Maui.FontManager: Error: Error loading font 'Assets/Fonts/MontserratSemiBold.ttf'.
> 
> System.InvalidOperationException: This operation is not supported for a relative URI.
>    at System.Uri.get_AbsolutePath()
>    at Microsoft.Maui.FontManager.FindFontFamilyName(String fontFile)
> Exception thrown: 'System.InvalidOperationException' in System.Private.Uri.dll
> Microsoft.Maui.FontManager: Error: Error loading font 'Assets/Fonts/MontserratSemiBold.otf'.
> 
> System.InvalidOperationException: This operation is not supported for a relative URI.
>    at System.Uri.get_AbsolutePath()
>    at Microsoft.Maui.FontManager.FindFontFamilyName(String fontFile)
> Exception thrown: 'System.InvalidOperationException' in WinRT.Runtime.dll
> Microsoft.Maui.FontRegistrar: Warning: Unable to load font 'MontserratRegular'.
> 
> System.InvalidOperationException: Operation is not valid due to the current state of the object.
>    at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
>    at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
>    at ABI.Windows.Storage.IApplicationDataStaticsMethods.get_Current(IObjectReference _obj)
>    at Windows.Storage.ApplicationData.get_Current()
>    at Microsoft.Maui.EmbeddedFontLoader.LoadFont(EmbeddedFont font)
>    at Microsoft.Maui.FontRegistrar.LoadEmbeddedFont(String cacheKey, String filename, String alias, Stream stream)
>    at Microsoft.Maui.FontRegistrar.GetFont(String font)
> Exception thrown: 'System.InvalidOperationException' in System.Private.Uri.dll
> Microsoft.Maui.FontManager: Error: Error loading font 'Assets/Fonts/MontserratRegular.ttf'.
> 
> System.InvalidOperationException: This operation is not supported for a relative URI.
>    at System.Uri.get_AbsolutePath()
>    at Microsoft.Maui.FontManager.FindFontFamilyName(String fontFile)
> Exception thrown: 'System.InvalidOperationException' in System.Private.Uri.dll
> Microsoft.Maui.FontManager: Error: Error loading font 'Assets/Fonts/MontserratRegular.otf'.
> 
> System.InvalidOperationException: This operation is not supported for a relative URI.
>    at System.Uri.get_AbsolutePath()
>    at Microsoft.Maui.FontManager.FindFontFamilyName(String fontFile)
> Exception thrown: 'System.InvalidOperationException' in WinRT.Runtime.dll
> Microsoft.Maui.FontRegistrar: Warning: Unable to load font 'MaterialDesignIcons'.
> 
> System.InvalidOperationException: Operation is not valid due to the current state of the object.
>    at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
>    at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
>    at ABI.Windows.Storage.IApplicationDataStaticsMethods.get_Current(IObjectReference _obj)
>    at Windows.Storage.ApplicationData.get_Current()
>    at Microsoft.Maui.EmbeddedFontLoader.LoadFont(EmbeddedFont font)
>    at Microsoft.Maui.FontRegistrar.LoadEmbeddedFont(String cacheKey, String filename, String alias, Stream stream)
>    at Microsoft.Maui.FontRegistrar.GetFont(String font)
> Exception thrown: 'System.InvalidOperationException' in System.Private.Uri.dll
> Microsoft.Maui.FontManager: Error: Error loading font 'Assets/Fonts/MaterialDesignIcons.ttf'.
> 
> System.InvalidOperationException: This operation is not supported for a relative URI.
>    at System.Uri.get_AbsolutePath()
>    at Microsoft.Maui.FontManager.FindFontFamilyName(String fontFile)
> Exception thrown: 'System.InvalidOperationException' in System.Private.Uri.dll
> Microsoft.Maui.FontManager: Error: Error loading font 'Assets/Fonts/MaterialDesignIcons.otf'.
> 
> System.InvalidOperationException: This operation is not supported for a relative URI.
>    at System.Uri.get_AbsolutePath()
>    at Microsoft.Maui.FontManager.FindFontFamilyName(String fontFile)
> The program '[5660] ActiveDirectorySearch.exe' has exited with code 3221226356 (0xc0000374).

Can you share an example project?
Thank you!

**Comment by BurkusCat** [comment]
Hey @jeremy-visionaid , I updated your original repro to use the latest version of MAUI and Win2D: https://github.com/BurkusCat/MauiFontImageSourceTest and I can see the icons working fine:

![image](https://github.com/dotnet/maui/assets/7528322/e498dc15-e147-4faa-b72a-87c9d7ca4a26)

Trying ionicons in my project works fine too. However, unpackaged apps with materialdesignicons show squares when used with a FontImageSource. I'll do more research as it at least seems promising I may be able to work around the issue with a different font file.

**Comment by jeremy-visionaid** [comment]
@BurkusCat Nice work, thanks for sharing! @AndreasReitberger was that sufficient for your case? Mine is essentially the same

**Comment by AndreasReitberger** [comment]
@jeremy-visionaid 
I'm using `MaterialDesignIcons`, so this is not working for me at the moment.
I made my project public, maybe you or @BurkusCat can have a look at it?

https://github.com/AndreasReitberger/ActiveDirectorySearchMaui

My tries are in the branch, main is untouched.

**Comment by jeremy-visionaid** [comment]
@AndreasReitberger I'm afraid I don't have the time to look at your repos, but the explicit Win2D reference is no longer required in 8.0,20

**Comment by AndreasReitberger** [comment]
Hi @jeremy-visionaid 
thanks for your update. I was able to try `8.0.20` in the meantime. After I had updated my project, the exceptions were gone.
However there are still no icons visible.

So I added the font for the icons to the `Maui` project directly. Now, the icons are shown. So I guess it is an issue with the way how I add it in the shared core library. I'll do further research on this and report back.

**Comment by AndreasReitberger** [comment]
Update: Adding the fonts at the core library as `MauiFont` instead of `EmbeddedResource` fixed that issue as well for me. So this can be closed.

**Comment by AndreasReitberger** [comment]
Must reopen this issue.
If adding the fonts in a `Shared` library class as `MauiFont`, the application still shows `[]` for the icons.
Only if I add the font also to the parent project, it works for unpackaged apps.

**Comment by AndreasReitberger** [comment]
I did some further research. I nailed it down to the `Nuget` creation. As long as the shared library is directly referenced, it works.
Once it is packaged as nuget, the font is missing.
I made a new issue for this with a repro and some further information.

https://github.com/dotnet/maui/issues/21771

@mattleibow @jeremy-visionaid 
Maybe you can have a look at this issue?
Thank you!

**Comment by hardikphd** [comment]
In our case, We are using Fontawesome as Symbol font, declared as MauiFont in main library. In all our custom controls, We can see symbols in unpackage app but where we are using 3rd party nugets like  Uranium UI (2.8.1), which has capability to pass your own Icon to their input fields, we dont see icons.  Here we are binding Icon like following

`                        <material:TextField Grid.Row="0" Title="Username"
                                            Text="{Binding UserName}" AutomationId="UserName" 
                                            Icon="{FontImageSource FontFamily={StaticResource SymbolFontFamily}, Glyph={StaticResource fa-user-circle}}" />
`
We don't see Icon for that control but on same page, we see icons for our control. (See buttons with Icons)

![image](https://github.com/dotnet/maui/assets/16522825/e9ca07d9-35aa-45f5-888e-966e1c1d1e17)

**Comment by GuidoNeele** [comment]
> In our case, We are using Fontawesome as Symbol font, declared as MauiFont in main library. In all our custom controls, We can see symbols in unpackage app but where we are using 3rd party nugets like Uranium UI (2.8.1), which has capability to pass your own Icon to their input fields, we dont see icons. Here we are binding Icon like following
> 
> ` <material:TextField Grid.Row="0" Title="Username" Text="{Binding UserName}" AutomationId="UserName" Icon="{FontImageSource FontFamily={StaticResource SymbolFontFamily}, Glyph={StaticResource fa-user-circle}}" />` We don't see Icon for that control but on same page, we see icons for our control. (See buttons with Icons)
> 
> ![image](https://private-user-images.githubusercontent.com/16522825/323229828-e9ca07d9-35aa-45f5-888e-966e1c1d1e17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MzUxODAsIm5iZiI6MTcxMzUzNDg4MCwicGF0aCI6Ii8xNjUyMjgyNS8zMjMyMjk4MjgtZTljYTA3ZDktMzVhYS00NWY1LTg4OGUtOTY2ZTFjMWQxZTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDEzNTQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzYTZlM2ExMTU2Y2ExNWRkZDgyMmMzNWIwNTZhYzI0YjYxNDBkNjRhZjlkNGJlMWVkNTkxMWNjNTk0MGFmYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fU0iv6WSWXcIwGh1MC7PnxqNw9-Z4Bn_uDVtsDbFfIs)
> 
> When we add another symbol library ionicons just for Uranium UI controls, We could see Icons in Uranium UI controls.

Yes this is so strange. ionicons is working but FontAwesome isn't.

![image](https://github.com/dotnet/maui/assets/1301586/9f96b251-0f40-490f-8609-b70f355f506a)

```xaml
<Button x:Name="CounterBtn"
        Clicked="OnCounterClicked"
        FontFamily="OpenSansSemibold"
        HorizontalOptions="Fill"
        ImageSource="{FontImage &#xf1b9;,
                                FontFamily=FontAwesome,
                                Color=White}"
        SemanticProperties.Hint="Counts the number of times you click"
        Text="Click me" />

<Button Clicked="OnCounterClicked"
        FontFamily="OpenSansSemibold"
        HorizontalOptions="Fill"
        ImageSource="{FontImage &#xf30c;,
                                FontFamily=ionicons,
                                Size=44}"
        SemanticProperties.Hint="Counts the number of times you click"
        Text="Click me" />

<Button Clicked="OnCounterClicked"
        FontFamily="OpenSansSemibold"
        HorizontalOptions="Fill"
        ImageSource="{FontImage Glyph={Static icons:FontAwesome.DumpsterFire},
                                FontFamily=ionicons,
                                Size=44}"
        SemanticProperties.Hint="Counts the number of times you click"
        Text="Click me" />
```

**Comment by hardikphd** [comment]
@GuidoNeele Just to clarify, Fontawesome is working for us in our own library with un-package app, 
It is not working with 3rd party custom control, (Uranium UI) in our case but ionicons is working with 3rd party custom control 
So, we are using Fontawesome for our controls and ionicons for 3rd party controls.

**Comment by GuidoNeele** [comment]
> @GuidoNeele Just to clarify, Fontawesome is working for us in our own library with un-package app, It is not working with 3rd party custom control, (Uranium UI) in our case but ionicons is working with 3rd party custom control So, we are using Fontawesome for our controls and ionicons for 3rd party controls.

It is? Would you perhaps have a working demo app? I've wasting hours today to get it working.

**Comment by GuidoNeele** [comment]
> [MauiApp1.zip](https://github.com/dotnet/maui/files/15042263/MauiApp1.zip) @GuidoNeele Here you go!! I had to make following changes done in project file
> 
> ![image](https://private-user-images.githubusercontent.com/16522825/324008415-269b06d5-509a-4343-968c-8dbfdf6cd24e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NDA0NjksIm5iZiI6MTcxMzU0MDE2OSwicGF0aCI6Ii8xNjUyMjgyNS8zMjQwMDg0MTUtMjY5YjA2ZDUtNTA5YS00MzQzLTk2OGMtOGRiZmRmNmNkMjRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDE1MjI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5NmY3MDU3OWI3NGJhZDk1MWYzZjZmMDc1MTM2NGY2Nzc1YjMxMjQ3ZGUxNDQ3ZGFiNGI2ZGVhN2JlZjkzYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m0ldyA1Xs3Bqlf_x56ZZnhiFBpL7cwALnsIn2GaKwtQ)
> 
> And I used following command to build the app on command prompt `dotnet build "./MauiApp1/MauiApp1.csproj" -c Release -f net8.0-windows10.0.19041.0 -p:RuntimeIdentifierOverride=win10-x64 /p:ErrorOnDuplicatePublishOutputFiles=false`
> 
> and I ran "MauiApp1.exe" generated in folder ...\MauiApp1\MauiApp1\bin\Release\net8.0-windows10.0.19041.0\win10-x64
> 
> Output: ![image](https://private-user-images.githubusercontent.com/16522825/324007867-31d2bfc6-05cf-46d5-8f37-e4243592c6ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NDA0NjksIm5iZiI6MTcxMzU0MDE2OSwicGF0aCI6Ii8xNjUyMjgyNS8zMjQwMDc4NjctMzFkMmJmYzYtMDVjZi00NmQ1LThmMzctZTQyNDM1OTJjNmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDE1MjI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYTdhYTY5YWE2ZTExNGQ1ZjRmZWRjOTJiNjY2MmMzMjc3NjFkOTMyMTcxNGY4NjU0NjgzNzYxOTRhMDczOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l77bWdG8ioDRi5j1beNRoc32baEArXh_bNIFqnDHrf8)
> 
> Here is how I used FontAwesome font ` <Label FontFamily="FontAwesome" HorizontalOptions="Fill" Text="&#xf30c;" HorizontalTextAlignment="Center" VerticalTextAlignment="Center"/>`

Thanks! Will give it a try.

**Comment by hardikphd** [comment]
@GuidoNeele 
In such case, you have to use custom control for button, Like  https://github.com/scriptBoris/ButtonSam.Maui and then it will work.
We are using our own custom control called CustomButton with similar functionality.

            <maui:Button x:Name="button" BackgroundColor="Aqua" CornerRadius="3">
                <HorizontalStackLayout Spacing="10">
                    <Label FontFamily="FontAwesome"
                           HorizontalOptions="Fill" TextColor="Black"
                           Text="&#xf30c;" HorizontalTextAlignment="Center" VerticalTextAlignment="Center"/>
                    <Label Text="Hello world"
                           TextColor="Black"
                           HorizontalTextAlignment="Center"/>
                </HorizontalStackLayout>
            </maui:Button>

**Comment by mattleibow** [comment]
This issue appears to be getting conflated with 2 separate issues (or maybe something else):

 - https://github.com/dotnet/maui/issues/19804
 - https://github.com/dotnet/maui/issues/21469

I am closing this as I still believe the real issue the OP had was fixed. If the remaining issues are not one of the 2, please open a new issue with a sample. Thanks!
