### ISSUE TITLE
[Bug] Maui-Blazor Project Template crashes in Release Mode 

### ISSUE THREAD

**Issue by aokocax** [dotnet/maui#2246]
### Description
I'm trying to run the base maui-blazor template in Visual Studio 2022 Preview 3 in release mode. In android devices the application crashes as soon as the .net intro screen passes.  (It works perfectly in debug mode)

### Steps to Reproduce

1. Create a new Maui-Blazor App 
 ![image](https://user-images.githubusercontent.com/1059475/130754080-67f85679-95b4-4d67-8772-854c001b2e59.png)

2. Run on release mode 
![image](https://user-images.githubusercontent.com/1059475/130754176-b020e0d7-e33f-4742-8d1a-2a1a49cfd7b2.png)

### Expected Behavior
No crash.
### Actual Behavior
The application crashes as soon as the .net intro screen passes.
### Basic Information

- Version with issue: .net 6 preview 7
- Last known good version: -
- IDE: Visual Studio 2022 Preview 3
- Platform Target Frameworks: Android 
 
  - Android: Android 9 (my phone arm64) , Android 7.1.2 (Nox virtual tablet x86)
  - UWP:   
- Android Support Library Version: 28
- Nuget Packages:
- Affected Devices: 

### Device Log
Time	Device Name	Type	PID	Tag	Message
08-25 10:01:27.911	Samsung SM-G9550	Info	3402	art	Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.companyname.MauiApp11-1/base.apk"],nativeLibraryDirectories=[/data/app/com.companyname.MauiApp11-1/lib/x86, /data/app/com.companyname.MauiApp11-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
  at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
  at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
  at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
  at void crc6488302ad6e9e4df1a.MauiAppCompatActivity.n_onCreate(android.os.Bundle) (MauiAppCompatActivity.java:-2)
  at void crc6488302ad6e9e4df1a.MauiAppCompatActivity.onCreate(android.os.Bundle) (MauiAppCompatActivity.java:46)
  at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6692)
  at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1118)
  at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2621)
  at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2729)
  at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
  at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1480)
  at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
  at void android.os.Looper.loop() (Looper.java:154)
  at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6198)
  at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
  at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:891)
  at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:781)

Time	Device Name	Type	PID	Tag	Message
08-25 10:01:27.911	Samsung SM-G9550	Info	3402	art	Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
  at void crc6488302ad6e9e4df1a.MauiAppCompatActivity.n_onCreate(android.os.Bundle) (MauiAppCompatActivity.java:-2)
  at void crc6488302ad6e9e4df1a.MauiAppCompatActivity.onCreate(android.os.Bundle) (MauiAppCompatActivity.java:46)
  at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6692)
  at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1118)
  at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2621)
  at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2729)
  at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
  at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1480)
  at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
  at void android.os.Looper.loop() (Looper.java:154)
  at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6198)
  at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
  at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:891)
  at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:781)

**Comment by AWildTeddyBear** [comment]
I also just ran across this problem and was able to reproduce it. The workaround mentioned https://github.com/dotnet/maui/issues/2246#issuecomment-907428054 seems to run without crashing, however, I cannot navigate to any pages because of it.

**Comment by hartez** [comment]
It may be totally unrelated, but we have seen that exception on startup in Forms - see https://github.com/xamarin/Xamarin.Forms/issues/8301 and https://github.com/xamarin/Xamarin.Forms/issues/6703.

**Comment by Asyvix** [comment]
@Eilon any updates in this issue? Could this be fixed in Preview9?

**Comment by aokocax** [comment]
I also tried on mac but same problem persists. I think there is a problem on the android side, probably related to proguard.
Unfortunately, unlike xamarin forms, we cannot disable proguard in maui to test.

**Comment by aokocax** [comment]
Thank you very much @Asyvix
It worked as you said. Also I only add<AndroidLinkMode>None</AndroidLinkMode> and It works like a charm :)

**Comment by Kazbek** [comment]
> @Eilon @aokocax @hartez I found a workaround. only need to add a few properties to your project settings.
> 
> `<AndroidLinkMode>None</AndroidLinkMode>`
> 
> and thats it!. now maui blazor app working.

Im tried to add this but even default template now give me error:

```
Error XAGJS7004	System.ArgumentException: An item with the same key has already been added.
   в System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   в System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   в Xamarin.Android.Tasks.TypeMapGenerator.GenerateRelease(Boolean skipJniAddNativeMethodRegistrationAttributeScan, List`1 javaTypes, String outputDirectory, ApplicationConfigTaskState appConfState)
   в Xamarin.Android.Tasks.GenerateJavaStubs.WriteTypeMappings(List`1 types, TypeDefinitionCache cache)
   в Xamarin.Android.Tasks.GenerateJavaStubs.Run(DirectoryAssemblyResolver res)
   в Xamarin.Android.Tasks.GenerateJavaStubs.RunTask()
   в Microsoft.Android.Build.Tasks.AndroidTask.Execute() в /Users/builder/azdo/_work/2/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:строка 17	Analytics	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.101-preview.10.59\tools\Xamarin.Android.Common.targets	1423	

```

Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.1.0 Preview 1.1

**Comment by SteveSandersonMS** [comment]
Reopening because the availability of a workaround isn't the quality bar we're going for :) This needs to be fixed.

**Comment by SilverioMiranda** [comment]
Same problem with MAUI preview 12, 21/01/2022

**Comment by jamesmontemagno** [comment]
I think that the templates should probably include "Release" settings that override the defaults for architecture types, linker settings, and more. The UI for Xamarin.iOS/Android projects do this normally, but the templates ship with defaults. I think we just need to sync with those teams to configure the templates.

1.) @jonathanpeppers @Redth @dalexsoto  thoughts as these apply to  ios/android project templates as well
2.) We should add documentation for these settings @davidbritch thoughts?

**Comment by jonathanpeppers** [comment]
If the workaround is `<AndroidLinkMode>None</AndroidLinkMode>`, then that isn't really a workaround. You can't really ship a `Release` build to an app store like that, the app size would be quite large.

I don't follow what would change in the templates here? We should figure out what the issue is?

The crash mentioned here: https://github.com/dotnet/maui/issues/4262

```
01-21 15:58:46.701  7867  7867 F crashpad: dlopen: dlopen failed: library "libandroidicu.so" not found: needed by /system/lib64/libharfbuzz_ng.so in namespace (default)
01-21 15:58:46.702  7783  7837 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4 in tid 7837 (ThreadPoolForeg), pid 7783 (nyname.mauiapp2)
01-21 15:58:46.770  7870  7870 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
01-21 15:58:46.771   284   284 I tombstoned: received crash request for pid 7837
01-21 15:58:46.772  7870  7870 I crash_dump64: performing dump of process 7783 (target tid = 7837)
01-21 15:58:46.777  7870  7870 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-21 15:58:46.777  7870  7870 F DEBUG   : Build fingerprint: 'google/sdk_gphone_x86_64/generic_x86_64_arm64:11/RSR1.201211.001/7027799:user/release-keys'
01-21 15:58:46.777  7870  7870 F DEBUG   : Revision: '0'
01-21 15:58:46.777  7870  7870 F DEBUG   : ABI: 'x86_64'
01-21 15:58:46.778  7870  7870 F DEBUG   : Timestamp: 2022-01-21 15:58:46+0000
01-21 15:58:46.778  7870  7870 F DEBUG   : pid: 7783, tid: 7837, name: ThreadPoolForeg  >>> com.companyname.mauiapp2 <<<
01-21 15:58:46.778  7870  7870 F DEBUG   : uid: 10155
01-21 15:58:46.778  7870  7870 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4
01-21 15:58:46.778  7870  7870 F DEBUG   : Cause: null pointer dereference
01-21 15:58:46.778  7870  7870 F DEBUG   :     rax 000070fc876bf820  rbx 000070fc876bfdc0  rcx 0000000000000000  rdx 000070fc876bf820
01-21 15:58:46.778  7870  7870 F DEBUG   :     r8  fffffffffffffdd0  r9  000070fc876bfe40  r10 0000000000000000  r11 000070fc8c34bb30
01-21 15:58:46.779  7870  7870 F DEBUG   :     r12 000070fc876bfbe0  r13 000070fce442b550  r14 000070fe54b03098  r15 0000000000000000
01-21 15:58:46.779  7870  7870 F DEBUG   :     rdi 000070fc876bfdc0  rsi 0000000000000000
01-21 15:58:46.779  7870  7870 F DEBUG   :     rbp 0000000000000000  rsp 000070fc876bfba0  rip 000070fce49048fc
01-21 15:58:46.838  7870  7870 F DEBUG   : backtrace:
01-21 15:58:46.838  7870  7870 F DEBUG   :       #00 pc 000000000065d8fc  /apex/com.android.art/lib64/libart.so (void art::StackVisitor::WalkStack<(art::StackVisitor::CountTransitions)0>(bool)+156) (BuildId: 7fbaf2a1a3317bd634b00eb90e32291e)
01-21 15:58:46.838  7870  7870 F DEBUG   :       #01 pc 000000000069b25d  /apex/com.android.art/lib64/libart.so (art::Thread::GetCurrentMethod(unsigned int*, bool, bool) const+157) (BuildId: 7fbaf2a1a3317bd634b00eb90e32291e)
01-21 15:58:46.838  7870  7870 F DEBUG   :       #02 pc 0000000000430fed  /apex/com.android.art/lib64/libart.so (art::JNI<false>::FindClass(_JNIEnv*, char const*)+765) (BuildId: 7fbaf2a1a3317bd634b00eb90e32291e)
01-21 15:58:46.838  7870  7870 F DEBUG   :       #03 pc 0000000000047e5a  /data/app/~~0Qm6D1S0sO3f1lwfakN0PA==/com.companyname.mauiapp2-08UokVCH5k_PlbZEH_hhkA==/split_config.x86_64.apk!libmono-android.release.so (offset 0x11e000) (java_interop_jnienv_find_class+26) (BuildId: 3d04f8b946590175e97b89aee2e3b19ceed4b524)
01-21 15:58:46.838  7870  7870 F DEBUG   :       #04 pc 00000000000128ac  <anonymous:41640000>
01-21 15:58:47.095   284   284 E tombstoned: Tombstone written to: /data/tombstones/tombstone_03
```

I'll try to repro and see if we can find out the cause. It kind of looks like `java_interop_jnienv_find_class` tried to locate a class that was linked away?

**Comment by jonathanpeppers** [comment]
We should hopefully have this fixed in the next MAUI preview.

The most precise workaround is to create a `ILLink.Descriptors.xml` file:
```xml
<linker>
    <assembly fullname="Mono.Android">
        <type fullname="Android.Runtime.InputStreamAdapter" preserve="methods" />
        <type fullname="Android.Runtime.InputStreamInvoker" preserve="methods" />
    </assembly>
</linker>
```
Put this in your `.csproj` as well:
```xml
<EmbeddedResource Include="ILLink.Descriptors.xml">
  <LogicalName>ILLink.Descriptors.xml</LogicalName>
</EmbeddedResource>
```
Details about the file format [here](https://github.com/dotnet/linker/blob/main/docs/data-formats.md).

**Comment by SilverioMiranda** [comment]
> We should hopefully have this fixed in the next MAUI preview.
> 
> The most precise workaround is to create a `ILLink.Descriptors.xml` file:
> 
> ```
> <linker>
>     <assembly fullname="Mono.Android">
>         <type fullname="Android.Runtime.InputStreamAdapter" preserve="methods" />
>         <type fullname="Android.Runtime.InputStreamInvoker" preserve="methods" />
>     </assembly>
> </linker>
> ```
> 
> Put this in your `.csproj` as well:
> 
> ```
> <EmbeddedResource Include="ILLink.Descriptors.xml">
>   <LogicalName>ILLink.Descriptors.xml</LogicalName>
> </EmbeddedResource>
> ```
> 
> Details about the file format [here](https://github.com/dotnet/linker/blob/main/docs/data-formats.md).

This fix wont work as expected.
Only works if you don't deployed any release version of maui before or with clean android emulator or app app with new ApplicationId

**Comment by jonathanpeppers** [comment]
@SilverioMiranda did you try to Clean or Rebuild? What you’re describing sounds like an incremental build issue, when adding the new file.

**Comment by SilverioMiranda** [comment]
@jonathanpeppers yes, i did Clean Solution and Rebuild. Now after you tell about incremental build issue i deleted bin and obj folders and worked like a charm

**Comment by aokocax** [comment]
For MAUI-Blazor project, I tried all the mentioned methods (clean, rebuild) but the application started to crash again.

https://github.com/aokocax/MauiBlazorLinker

**Comment by SteveSandersonMS** [comment]
@aokocax I think there's a mistake in your file https://github.com/aokocax/MauiBlazorLinker/blob/master/MauiBlazorLinker/ILLink.Descriptors.xml. Its contents don't look like what was suggested by @SilverioMiranda above.

**Comment by sunil04ce** [comment]
> We should hopefully have this fixed in the next MAUI preview.
> 
> The most precise workaround is to create a `ILLink.Descriptors.xml` file:
> 
> ```
> <linker>
>     <assembly fullname="Mono.Android">
>         <type fullname="Android.Runtime.InputStreamAdapter" preserve="methods" />
>         <type fullname="Android.Runtime.InputStreamInvoker" preserve="methods" />
>     </assembly>
> </linker>
> ```
> 
> Put this in your `.csproj` as well:
> 
> ```
> <EmbeddedResource Include="ILLink.Descriptors.xml">
>   <LogicalName>ILLink.Descriptors.xml</LogicalName>
> </EmbeddedResource>
> ```
> 
> Details about the file format [here](https://github.com/dotnet/linker/blob/main/docs/data-formats.md).

This worked for me.
<ItemGroup>
    <EmbeddedResource Include="ILLink.Descriptors.xml">
      <LogicalName>ILLink.Descriptors.xml</LogicalName>
    </EmbeddedResource>
 </ItemGroup>
