### ISSUE TITLE
[Windows] On .NET MAUI 9.0 Preview 4, a modal full screen window is not properly maximized

### ISSUE THREAD

**Issue by janne-hmp** [dotnet/maui#22784]
### Description

On Windows in 9.0 Preview 4, a modal full screen window produced with

```
#if WINDOWS
            .ConfigureLifecycleEvents(events =>
            {
                // Make sure to add "using Microsoft.Maui.LifecycleEvents;" in the top of the file 
                events.AddWindows(windowsLifecycleBuilder =>
                {
                    windowsLifecycleBuilder.OnWindowCreated(window =>
                    {
                        window.ExtendsContentIntoTitleBar = false;
                        var handle = WinRT.Interop.WindowNative.GetWindowHandle(window);
                        var id = Microsoft.UI.Win32Interop.GetWindowIdFromWindow(handle);
                        var appWindow = Microsoft.UI.Windowing.AppWindow.GetFromWindowId(id);
                        switch (appWindow.Presenter)
                        {
                            case Microsoft.UI.Windowing.OverlappedPresenter overlappedPresenter:
                                overlappedPresenter.SetBorderAndTitleBar(false, false);
                                overlappedPresenter.Maximize();
                                break;
                        }
                    });
                });
            })
#endif            
```

does not fully maximize itself, but leaves a blank space for where the title bar should be. Non-modal windows seem to work fine. The modal window is shown using the following code:

```
            var gamePage = new GamePage(this);
            await App.Current.MainPage.Navigation.PushModalAsync(gamePage);
```

![Screenshot 2024-06-02 224231](https://github.com/dotnet/maui/assets/53081197/91b7177a-dade-4adf-9a30-de101e171797)

### Link to public reproduction project repository

https://github.com/hyvanmielenpelit/GnollHack

### Version with bug

9.0.0-preview.4.10690

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

No.

**Comment by PureWeen** [comment]
@janne-hmp does this also happen on net8?

**Comment by janne-hmp** [comment]
> @janne-hmp does this also happen on net8?

I'm not sure, since the game uses .NET 9.0 features and also I do not have .NET 8.0 installed, which both make it difficult to check something like that. At least the latest version in .NET 9.0 works incorrectly, so perhaps .NET 8.0 behaves similarly.

**Comment by janne-hmp** [comment]
I can also confirm that if I use `PushAsync` instead of `PushModalAsync`, the content page is of the right size (entire full screen). So the problem is just with the modal window.

**Comment by janne-hmp** [comment]
This is also relatively easy to reproduce:

1. Make the default MAUI app
2. Create a new MAUI ContentPage named ModalTestPage.
3. Change ModalTestPage's background color to Beige by adding to the page's XAML: `BackgroundColor="Beige"` .
4. Add the following code to the MainPage button:
```
            var modalPage = new ModalTestPage();
            Navigation.PushModalAsync(modalPage);
```
5. Build and start the app.
6. The modal page (beige) does not cover the whole window: Top still shows the main page underneath (white, with Home text):

![Screenshot 2024-06-08 202445](https://github.com/dotnet/maui/assets/53081197/5bed160b-1660-4c6b-85d5-34655527783e)

**Comment by janne-hmp** [comment]
> @janne-hmp does this also happen on net8?

Just managed to test this also on .NET 8, and it works there just like in .NET 9 Preview. In the sample app, there seem to be big title bar on MainPage (says "Home") and a small title bar on ModalTestPage (says "MauiApp2"), which are shown on the top of each other.

**Comment by janne-hmp** [comment]
It would be great to get a fix to this. Among other things, various page transition animations malfunction by not handling the top titlebar, leaving that part of the page cut off from the animation. Also, when recording the game with some software, the titlebar area is left gray; you cannot click the top area with cursor either.

After some research, I also found out the following: Page's PlatformView is ContentPanel on Windows. The parent of this ContentPanel is RootNavigationView. The AppBarTitleHeight property of RootNavigationView is set incorrectly to 32 (at least with modal pages shown with PushModalAsync), but I haven't found a way to change that value. It probably needs to be set directly by MAUI to its correct value. Not sure if this is the entire problem, though.

**Comment by HectorCF16** [comment]
Same issue here. We are making a Kiosk application and we're waiting to see how to fix this.
![image](https://github.com/user-attachments/assets/0555ae60-5637-4820-9ea2-d65fe5eb1e38)

**Comment by janne-hmp** [comment]
For the time being, you can set the content page's layout's (e.g. a grid at the root) top margin to -32, but that is not a perfect fix, since you cannot then click the top 32 pixels of the page in that case. But if there's nothing clickable there in your app, it may be ok until the real fix comes by.

@davidortinau This would be another important thing to prioritize in .NET MAUI 9.0 / by the Windows team. It is probably a simple fix when you find the right place.

**Comment by HectorCF16** [comment]
Thank you very much Jane, It didn't work for me as my Content page is not fullscreen and the negative margin applies to the "¿Cómo quieres pagar?" page and not to the shadow. So, as I can't apply the margin to the whole content page, but thanks a lot.

**Comment by RuddyOne** [comment]
Also having this issue and it is really bad for a production application. Can we get this basic functionality fixed?

**Comment by janne-hmp** [comment]
@davidortinau Any update what's the status on this? I still think that this should really be prioritized on the Windows side, as it impacts every full screen application with modal pages. Happy to help out, if need be.

**Comment by janne-hmp** [comment]
As per the steps to produce, you don't need the game here, you can just use the default MAUI app and add a few lines of code:

1. Make the default MAUI app
2. Create a new MAUI ContentPage named ModalTestPage.
3. Change ModalTestPage's background color to Beige by adding to the page's XAML: `BackgroundColor="Beige" `.
4. Add the following code to the MainPage button:
```
            var modalPage = new ModalTestPage();
            Navigation.PushModalAsync(modalPage);
```
5. Add to the top of MauiProgram.cs the following:

`using Microsoft.Maui.LifecycleEvents;`

and add to builder the following:

```
#if WINDOWS
                .ConfigureLifecycleEvents(events =>
                {
                    // Make sure to add "using Microsoft.Maui.LifecycleEvents;" in the top of the file 
                    events.AddWindows(windowsLifecycleBuilder =>
                    {
                        windowsLifecycleBuilder.OnWindowCreated(window =>
                        {
                            window.ExtendsContentIntoTitleBar = false;
                            var handle = WinRT.Interop.WindowNative.GetWindowHandle(window);
                            var id = Microsoft.UI.Win32Interop.GetWindowIdFromWindow(handle);
                            var appWindow = Microsoft.UI.Windowing.AppWindow.GetFromWindowId(id);
                            switch (appWindow.Presenter)
                            {
                                case Microsoft.UI.Windowing.OverlappedPresenter overlappedPresenter:
                                    overlappedPresenter.SetBorderAndTitleBar(false, false);
                                    overlappedPresenter.Maximize();
                                    break;
                            }
                        });
                    });
                })
#endif            
```
6. Build and start the app.
7. Press the button.
8. The modal page (beige) does not cover the whole window: Top still shows the main page underneath (white, with Home text).

Does this enable to have a look, or do you really need a full reproduction repository?

**Comment by Foda** [comment]
Hello! This issue is caused by the way I checked for the Window style. It should be fixed in the 1.6 WinAppSDK bump: https://github.com/dotnet/maui/pull/24266

**Comment by RuddyOne** [comment]
I have also tried  #24266 and am still seeing the same issue as the OP.

**Comment by janne-hmp** [comment]
> Hello! This issue is caused by the way I checked for the Window style. It should be fixed in the 1.6 WinAppSDK bump: #24266

I recently updated to .NET MAUI 9.0 RC1 (along with Visual Studio 2022 17.12 Preview 2.0), and the issue still persists in RC1. Does RC1 use WinAppSDK 1.6 on Windows, or do we need to somehow upgrade it separately so that MAUI Windows will start using it?

**Comment by janne-hmp** [comment]
Applying the comment (i.e. just changing the Windows build number) leads to a malfunctioning app that does not start. 19041 works fine. Perhaps 22621 is not very well tested yet:

![image](https://github.com/user-attachments/assets/d1294a9f-ddb2-4b23-a822-3c63312a582e)

**Comment by Takym** [comment]
> This issue should be fixed by this change: https://github.com/dotnet/maui/pull/24266/files#diff-60a1bc7c3c705e23af11c60ea9e5ccdd66a6e1821d82cbcad05d3648dacf77d5 (AFAIK).
> 
> So one would have to compile #24266. That is, [upgrading to](https://github.com/dotnet/maui/pull/24266#issuecomment-2341609579) WinAppSkd 1.6 is probably not sufficient.

Thank you for telling me. I misunderstood.

**Comment by janne-hmp** [comment]
As long as I have `<WindowsSdkPackageVersion>10.0.19041.38</WindowsSdkPackageVersion>` in the project file, I still get the aforementioned internal exception also in 19041, both with and without `<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.6.240829007" />` As mentioned above, this also happened with `WindowsSdkPackageVersion` being 10.0.22621.38. So it seems to be something about `WindowsSdkPackageVersion` ending 38.

**Comment by RuddyOne** [comment]
Has anyone got this working? I cant seem to see this issue being fixed when trying to update the Windows SDK package version etc.

**Comment by janne-hmp** [comment]
I think we may need to wait until WinAppSDK 1.6 starts to be used by .NET MAUI on Windows. Does anybody know when this upgrade is planned to happen?

**Comment by Takym** [comment]
Is this issue fixed by #24266?

**Comment by Takym** [comment]
I have applied the workaround for #22894 and it seems fine.

Fork for the repro repo: https://github.com/Takym/WindowsFullScreenModalPageSizeBug/commit/dbda22b2ddefcd26b7fa74ed483cfadd5c09f2a3#diff-0a531dde851e9737d500b3d99b4f524dbd1d2023874856a961bb8e6528c96f99R21-R31

**Comment by Takym** [comment]
I have tested with the nightly build and it still has a problem with a title bar. I propose again adding a new lifecycle event called after MauiWinUIWindow was instantiated and before a window scope was instantiated (https://github.com/dotnet/maui/issues/22894#issuecomment-2156251399). So, by using a new event, your ExtendsContentIntoTitleBar value affects the NavigationRootManager constructor.

### Versions
* .NET Runtime: `net9.0-windows10.0.26100.0`
* .NET MAUI: `9.0.20-ci.main.24573.3`
* Windows SDK: `10.0.26100.57`
* Windows App SDK: `1.6.241114003`

### Reproduction Repository
<https://github.com/Takym/DoublyTitleBarsInMaui/commit/a4290239443bd26ef5ebf2f2eb2cc67825126a41>
<https://github.com/Takym/WindowsFullScreenModalPageSizeBug/commit/1c580880f34508e8f2f4d7095bd12abbb1db4836>

### Screenshots
![DoublyTitleBarsInMaui](https://github.com/user-attachments/assets/0750a588-7322-4758-a6f1-9c354fa30845)
![WindowFullScreenModalPageBug](https://github.com/user-attachments/assets/83eafd14-ff0c-403d-ae62-e6d1b2d23494)

**Comment by Takym** [comment]
I found another workaround by setting the title bar visibility as hidden with reflection. However, this is unsafe.
https://github.com/Takym/DoublyTitleBarsInMaui/blob/9ef6d23d354115f2e1c57431e4bd47a5af1cb847/DoublyTitleBarsInMaui/App.xaml.cs#L20-L23

**Comment by ArcanorCode** [comment]
I got exactly the same problem now on android. 
I was using my app in full mode with .NET 8.0 just fine. I updated now my project to .NET 9.0 and, when i use `PushModalAsync()`, the next page is no more on full mode.

**Comment by mcyenikoylu** [comment]
The problem persists in .NET 9.0.

- net9.0-windows10.0.19041.0
- Windows 11
- Visual Studio 2022 17.14

**Comment by Takym** [comment]
I tested a year ago; maybe a bug of #22894 persists, too.

PS: This may not be something I should write here, but when I retest with MAUI version 9.0.120 today, I encounter a build error stating that "HybridWebView.js" does not exist in the NuGet package cache. Commit: https://github.com/Takym/DoublyTitleBarsInMaui/commit/b6f28c787782756639724abf24fce647294e0575 (reverted by https://github.com/Takym/DoublyTitleBarsInMaui/commit/8c2e26418f7ec549de32f657f6711e5ec570cbac)

**Comment by janne-hmp** [comment]
I can confirm that this problem persists on my side, too, in the latest .NET MAUI.

**Comment by Takym** [comment]
My opinion, which I proposed last year, on resolving this problem by adding a new API is here: https://github.com/dotnet/maui/issues/22894#issuecomment-2156251399
