### ISSUE TITLE
Editor and ScrollView problems in iOS

### ISSUE THREAD

**Issue by geertgeerits** [dotnet/maui#22946]
### Description

1. Editor: HorizontalOptions does not work.
2. ScrollView: Orientation="Vertical": The orientation is wrong when the device is rotated from landscape to portrait. The orientation is changed to horizontal.

### Steps to Reproduce

Open the repository and click the 'Click me' button.

### Link to public reproduction project repository

https://github.com/geertgeerits/MauiBugEditor

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS tested from version 15

### Did you find any workaround?

No

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.11.0 Preview 1.1 (8.0.40&8.0.21). Can repro on iOS platform with sample project.

**Comment by karthikraja-arumugam** [comment]
**Issue 1:** Since the parent grid is set to center alignment, the editor is aligned according to its size. If you want the editor to occupy the entire width, set the grid's horizontal options to "Fill" so the editor can take up the available space.
```
    <Grid
        RowDefinitions="Auto, *, Auto"
        ColumnDefinitions="130*, 100, 130*, 1"
        HorizontalOptions="Fill"
        Margin="0,0,4,5">

       ...
</Grid>
```

**Issue 2:** There doesn't appear to be any issue when changing device orientation at runtime. Could you please provide additional details, such as a screenshot or video, for better clarity on the issue?

**Comment by geertgeerits** [comment]
HorizontalOptions="Center" to HorizontalOptions="Fill" makes no difference. The error remains. Tested on an iPad with iOS 17.7.
See images on the project repository.

**Comment by geertgeerits** [comment]
The first problem is solved with that but not the second. When you press the 'Click me' key in vertical position you see the full text. Turn the device to horizontal position and then back to vertical position then you notice that the text is not displayed completely. On the iPad the text is lost after OOOOOO-P. So the letters P, Q, R, S, T are not displayed.

**Comment by karthikraja-arumugam** [comment]
@geertgeerits, The issue with horizontal scrolling has been resolved in the latest .NET 9 package. Could you please verify this with .NET 9?

**Comment by geertgeerits** [comment]
Hi,
The error is still there: ScrollView: Orientation="Vertical": The orientation is wrong when the device is rotated from landscape to portrait. The orientation is changed to horizontal.
When entering a text (click the 'Click me' button) in portrait position, then turn the device to landscape position and then back to portrait position, you wil see that there is text missing.  Link to public reproduction project repository:
https://github.com/geertgeerits/MauiBugEditor

Visual Studio 2022 Preview: version 17.12.0 Preview 5.0
Microsoft.Maui.Controls: version 9.0.0-rc.2.24503.2
Microsoft.Maui.Controls.Compatibility: version 9.0.0-rc.2.24503.2

**Comment by KarthikRajaKalaimani** [comment]
This issue is not reproduced on latest maui version v9.0.90 on iOS (iPad A16 iOS 18.5). I have attached the video for reference. 

https://github.com/user-attachments/assets/8a554269-c3f2-483e-8184-c71ed27bee74

**Comment by geertgeerits** [comment]
Hi,
Thanks for the bug fix. It works as it should.
Tested on Visual Studio 2022 version 17.14.11 and microsoft.maui.controls version 9.0.90.
