### ISSUE TITLE
Grid with auto width columns overflows its container 

### ISSUE THREAD

**Issue by RsZoli** [dotnet/maui#23735]
### Description

![111](https://github.com/user-attachments/assets/d3e8f0cc-f329-4012-8125-458801774900)

The lightblue background indicates a stacklayout, the gold/lightgreen/pink trio is a grid with 3 columns, each set to auto width!

The 3 columns each has a label with linebreakmode set to middletruncation, yet this does not happen, the grid overflows its container!

However, if i remove the auto width from the 2 outside columns, the linkebreakmode kick in, but it should not be, since there is plenty space for the grid to grow!

![222](https://github.com/user-attachments/assets/c31a6e82-a390-4848-b8b8-e39b8ee6dd41)

### Steps to Reproduce

Create a new .NET MAUI app, put a 3 coulm Grid inside a StackLayout in a ContentPage, set the Grid's columns to auto with and observe!

### Version with bug

8.0.61 SR6.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

**Comment by RsZoli** [comment]
Here you go: [https://github.com/RsZoli/GitHubRepros](url)

![Screenshot_1722267083](https://github.com/user-attachments/assets/fa0dd841-70cf-4454-9801-39ad48f027c0)

**Comment by ninachen03** [comment]
I can repro this issue at Android platform on the latest 17.11.0 Preview 5.0 (8.0.70 & 8.0.61 &8.0.3)

**Comment by FlavioGoncalves-Cayas** [comment]
@mattleibow Please, can you guys do something about this? 
You pretty much tell everyone to use Grids instead of StackLayouts if we want to have child elements to be constrained in their size, but somehow not even the Grid works properly. 
Why should an Auto column ever let it's child render larger than the grid itself?

**Comment by michiel-nwa** [comment]
According to https://github.com/dotnet/maui/issues/10494#issuecomment-1269199076  this is expected behaviour.  It seems Auto is pretty much only usable for fixed with items and just save you from duplicating the size explicitly.

For your specific case I guess  *,auto,* should work,  but there doesn't seem to be anything generic that performs like you would expect (basically HTML table layout logic that optimizes your grid to make the best use of available space)

**Comment by FlavioGoncalves-Cayas** [comment]
@hartez you said in the linked comment that this is by design. And sure the label can measure with infinite space, that's fine. But shouldn't the arrange step of the layout process limit the Labels width to something that does not break the Grids bounds and still fits the element with the fixed size.

**Comment by michiel-nwa** [comment]
@FlavioGoncalves-Cayas for that specific case I think you can do:
```<Grid HorizontalOptions="Start" ColumnDefinitions="*,42" ColumnSpacing="16">```

**Comment by FlavioGoncalves-Cayas** [comment]
Doesn't work. That will always position the red box at the end. But I want it to always be next to the label independent of the labels width

**Comment by RsZoli** [comment]
> According to [#10494 (comment)](https://github.com/dotnet/maui/issues/10494#issuecomment-1269199076) this is expected behaviour. It seems Auto is pretty much only usable for fixed width items and just save you from duplicating the size explicitly.
> 
> For your specific case I guess _,auto,_ should work, but there doesn't seem to be anything generic that performs like you would expect (basically HTML table layout logic that optimizes your grid to make the best use of available space)

Okay, but for me, the truncation is the bigger issue here!

**Comment by michiel-nwa** [comment]
@RsZoli sorry messed up my formatting, intended to write `*,auto,*`    I think that also fixes the truncation.   Just limits the two elements to be the same width. (which may look extremely weird if one of the strings is much shorter than the other)

**Comment by RsZoli** [comment]
> [@RsZoli](https://github.com/RsZoli) sorry messed up my formatting, intended to write `*,auto,*` I think that also fixes the truncation. Just limits the two elements to be the same width. (which may look extremely weird if one of the strings is much shorter than the other)

Sadly, that doesnt look good for my case!

**Comment by hartez** [comment]
This is not a bug, this is just what "Auto" in a Grid Column means. What you're expecting them to do (allocate the column space based on the measurement of _all_ of the Labels in the row) can't happen for a couple reasons. Each cell of a Grid can have more than one item of content in it, and columns can span multiple rows. Accounting for those conditions means that automatic sizing based on flexible sizing of content is at best an expensive recursive process, and at worst impossible. 

But all is not lost! .NET MAUI has a whole layout type dedicated to handling "flexible sizing of content": [FlexLayout](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/layouts/flexlayout?view=net-maui-8.0). To achieve the layout you want, you can do something like this:

```xaml
<FlexLayout FlexLayout.Wrap="NoWrap"
			JustifyContent="Center">

	<Label Text="Left Side Text"
		   HorizontalTextAlignment="End"
		   FlexLayout.AlignSelf="Start"
		   BackgroundColor="Orange"
		   LineBreakMode="MiddleTruncation" />

	<Label FlexLayout.Shrink="0"
		   Text=" - "
		   BackgroundColor="Green" />

	<Label Text="Right Side Text"
		   HorizontalTextAlignment="Start"
		   FlexLayout.AlignSelf="End"
		   LineBreakMode="MiddleTruncation"
		   BackgroundColor="Magenta" />

</FlexLayout>
```  

Doing that with several variations on the length of the text yields this:

![Image](https://github.com/user-attachments/assets/a59bd88d-90a0-44cf-8f22-e0027dba8140)

**Comment by RsZoli** [comment]
@hartez Thank you for your answer, i will definetly change my layout per your recommendation!

However my main problem is not the sizing of Grid cells rather than the trail truncation which doesn't happen when needed and happen when should not!

**Comment by hartez** [comment]
I don't know what to tell you, it's not a bug.  Auto Columns are not going to produce truncated text the way you want; that's just not how they work. There's another Layout which does precisely what you're asking for. This issue should be closed.

**Comment by RsZoli** [comment]
@hartez While i greatly appreciate your solution, which i have already implemented i cannot agree with you!

Per the documentation, the Auto column should: "Auto – the row height or column width is autosized based on the cell contents (Auto in XAML)." It does not mean that a Grid should overflow its container!

On the other issue, it doesn't work! In my 3rd example there is a truncation that should be happening, since there is plenty of space for the Auto column to grow4 It seams to me like if there would be a truncation first, and the Auto column measures the truncated Label, but it this case, what is the truncation based on?

I apologise in advance, the english is not my first language and many times i cannot convey perfertly what i mean, but i hope you can get the basics!

**Comment by FlavioGoncalves-Cayas** [comment]
> It does not mean that a Grid should overflow its container!

100% agree on this statement. And it shouldn't be hard to track the width of each column so you can limit the width of the Auto columns  to the remaining space (at least when there is only 1 Auto column).

**Comment by wbv-profile** [comment]
Still reproduces on `main` @ `bc3095fa`.

### Mechanism

An `Auto` column is measured with an **unbounded** width, regardless of the constraint the `Grid` itself was given:

https://github.com/dotnet/maui/blob/main/src/Core/src/Layouts/GridLayoutManager.cs#L1052

```csharp
else if (TreatCellWidthAsAuto(cell))
{
    cell.MeasureWidth = double.PositiveInfinity;
}
```

The child's desired width becomes the column's width, and nothing clamps it back to the grid's own constraint — so the child is arranged outside the container.

### Repro

Against `src/Core/tests/UnitTests` (no device needed) — one `Auto` column, one child wanting 1000pt, grid constrained to 300pt:

```csharp
var col = Substitute.For<IGridColumnDefinition>();
col.Width.Returns(GridLength.Auto);
// ... grid with that single column, single 100pt row

var child = LayoutTestHelpers.CreateTestView(new Size(1000, 100));
var manager = new GridLayoutManager(grid);
manager.Measure(300, 100);
manager.ArrangeChildren(new Rect(0, 0, 300, 100));
```

Observed:

| | value |
|---|---|
| grid constraint | 300 |
| width offered to child | **∞** |
| child's arrange rect | **1000** x 100 |

### Related

#10046 is the same defect in `HorizontalStackLayoutManager`, which offers `double.PositiveInfinity` to every child (`HorizontalStackLayoutManager.cs#L30`); `VerticalStackLayoutManager.cs#L31` does it on the height axis. All three share the shape: *measure the child unbounded, then never reconcile the result against the container's own constraint.*

That shared shape is why these reproduce in combination — a `Grid` with `Auto` columns inside a `StackLayout` compounds it — and why fixing one manager in isolation will leave the nested cases still overflowing.

**Comment by hartez** [comment]
It still reproduces because this is _by design_. As I mentioned upthread (years ago now), this is how "Auto" works. This issue should be closed.

**Comment by RsZoli** [comment]
@hartez and i mentioned you (years ago) that a child element should never overflow its parent, so no, it should not be closed!
