### ISSUE TITLE
WMC1006 compile error for Windows MAUI .NET 9 project when referencing Microsoft.Identity.Client.Desktop

### ISSUE THREAD

**Issue by superwilly1** [dotnet/maui#25883]
### Description

https://github.com/dotnet/windowsdesktop/issues/4789

Our app uses MSAL to login, using the Microsoft.Identity.Client packages.
This used to work in .NET8, but we updated our app to .NET9 now, and on Windows we get compile errors:

```
Cannot resolve Assembly or Windows Metadata file 'Type universe cannot resolve assembly: System.Xaml, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.'
Could not copy the file "C:\temp\NET9MAUIWindowsIssue\NET9MAUIWindowsIssue\obj\Debug\net9.0-windows10.0.19041.0\win10-x64\Platforms\Windows\App.xbf" because it was not found.
```

### Steps to Reproduce

1. Create a new MAUI project.
2. Add a NuGet package reference to Microsoft.Identity.Client.Desktop:
`<PackageReference Include="Microsoft.Identity.Client.Desktop" Version="4.66.2" />`
3. Note that the app cannot be compiled on Windows.

This zip file contains the above steps, just compile it on Windows and notice the compile errors:
[NET9MAUIWindowsIssue.zip](https://github.com/user-attachments/files/17773771/NET9MAUIWindowsIssue.zip)

I am not sure if this is an issue with MAUI or with Microsoft.Identity.Client, but since it worked on MAUI with .NET8, I assume it is a MAUI related issue.
Also created an issue for Microsoft.Identity.Client: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4993

### Version with bug

.NET 9 and WinUI
I'm able to reproduce this on a blank WinUI APP

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.93 SR9.3

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

```xml

<ItemGroup>
		<DefaultReferenceExclusion Include="WindowsFormsIntegration" />
	</ItemGroup>

	<Target Name="RemoveWindowsFormsIntegration" BeforeTargets="MarkupCompilePass1" AfterTargets="ResolveAssemblyReferences">
		<ItemGroup>
			<_referenceExclusion Include="@(DefaultReferenceExclusion)">
				<AssemblyName>%(DefaultReferenceExclusion.Identity)</AssemblyName>
			</_referenceExclusion>
			<ReferencePath Remove="@(_referenceExclusion)" MatchOnMetadata="AssemblyName" />
		</ItemGroup>
	</Target>


```

### Relevant log output

```shell
1>------ Build started: Project: NET9MAUIWindowsIssue, Configuration: Debug Any CPU ------
1>C:\temp\NET9MAUIWindowsIssue\NET9MAUIWindowsIssue\NET9MAUIWindowsIssue.csproj : XamlCompiler error WMC1006: Cannot resolve Assembly or Windows Metadata file 'Type universe cannot resolve assembly: System.Xaml, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.'
1>Skipping analyzers to speed up the build. You can execute 'Build' or 'Rebuild' command to run analyzers.
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5322,5): error MSB3030: Could not copy the file "C:\temp\NET9MAUIWindowsIssue\NET9MAUIWindowsIssue\obj\Debug\net9.0-windows10.0.19041.0\win10-x64\Platforms\Windows\App.xbf" because it was not found.
1>Done building project "NET9MAUIWindowsIssue.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 11:06 and took 06,247 seconds ==========
```

**Comment by DevDachi** [comment]
We're encountering the same issue that's hindering our .NET 9 migration


2>C:\repos\MauiApp1\MauiApp1\MauiApp1.csproj : XamlCompiler error WMC1006: Cannot resolve Assembly or Windows Metadata file 'Type universe cannot resolve assembly: System.Xaml, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.'
2>CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point
2>C:\repos\MauiApp1\MauiApp1\Platforms\Windows\App.xaml.cs(19,18,19,37): error CS1061: 'App' does not contain a definition for 'InitializeComponent' and no accessible extension method 'InitializeComponent' accepting a first argument of type 'App' could be found (are you missing a using directive or an assembly reference?)

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using Visual Studio 17.13 Preview 1( 9.0.10 & 8.0.93 & 8.0.100). Can repro this issue on Windows platform. And 8.0.100 & 8.0.93 work fine.

**Comment by PureWeen** [comment]
I'm able to reproduce this issue on a blank WinUI app (without MAUI) 

So, pretty sure this issue has nothing to do with MAUI directly

**Comment by PureWeen** [comment]
https://github.com/dotnet/windowsdesktop/issues/4789

**Comment by deialsc** [comment]
Same happens to me as soon as i add NAudio package. If i remove it, the error is gone...

**Comment by jonmdev** [comment]
> Same happens to me as soon as i add NAudio (2.2.1) package. If i remove it, the error is gone... Just to add NAudio.Core (2.2.1) package does not raise a problem

Thanks. I had the same issue. Removing NAudio for now solved this bug for m.

**Comment by PureWeen** [comment]
This should now be resolved with the latest release of the .NET 9 SDK

**Comment by justummar** [comment]
This still does not seem to be fixed, every time I create a brand-new project using the C# .NET MAUI Blazor Hybrid and Web App template, I get the following warning.

Cleaning and rebuilding the solution does not resolve it, I checked the dependencies too.

Cannot resolve Assembly or Windows Metadata file 'C:\LocalDevelopment\AutismTherapyCentreApp\AutismTherapyCentreApp.Shared\bin\Debug\net9.0\AutismTherapyCentreApp.Shared.dll'

This is in a completely empty directory and everything on my machine is updated with dotnet version 9.0.102
Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.12.4
