### ISSUE TITLE
XAML

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#26808]
### Description

Using XAML values of {StaticResource ...} causes faults in Android released code but not in Debug code.
 

### Steps to Reproduce

1. Clone the repository
2. Build a Debug version and run on Android and you should see this:
3. ![Image](https://github.com/user-attachments/assets/8db82c11-38f2-493b-8491-05fc01a2478e)
4. Build a Release version and run it on Android and it will crash during initialization.

### Link to public reproduction project repository

https://github.com/david-maw/Community-StaticResource.git

### Version with bug

9.0.21 SR2.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 13

### Did you find any workaround?

No

### Relevant log output

```shell

```

**Comment by Ying-6** [comment]
This issue has been verified using Visual Studio 17.13.0 Preview 2.1 (9.0.21 & 9.0.14 & 8.0.100). Can repro this issue on Android platform.

**Comment by kubaflo** [comment]
@PureWeen I'm pretty sure it is fixed by this PR: https://github.com/dotnet/maui/pull/26465

@StephaneDelcroix I've tested before and after a merge and it works for me :)

**Comment by david-maw** [comment]
It still fails for me.

I'm running the latest preview I can see, 17.13.0 Preview 2.1 and I see no available nuget package updates or workload updates. Am I missing something?

The workloads I have are:
```
Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------------------------------------------------
android                    35.0.24/9.0.100        SDK 9.0.200-preview.0, VS 17.13.35617.110, VS 17.12.35527.113
aspire                     8.2.2/8.0.100          SDK 9.0.200-preview.0, VS 17.12.35527.113
ios                        18.2.9170/9.0.100      SDK 9.0.200-preview.0, VS 17.13.35617.110, VS 17.12.35527.113
maccatalyst                18.2.9170/9.0.100      SDK 9.0.200-preview.0, VS 17.13.35617.110, VS 17.12.35527.113
maui                       9.0.0/9.0.100          SDK 9.0.200-preview.0
maui-windows               9.0.0/9.0.100          SDK 9.0.200-preview.0, VS 17.13.35617.110, VS 17.12.35527.113
```

The packages I have configured with the project are:
```
    <PackageReference Include="CommunityToolkit.Maui" Version="10.0.0" />
    <PackageReference Include="Microsoft.Maui.Controls" Version="9.0.21" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.0" />
```

**Comment by gvhung** [comment]
I'm running the latest Visual Studio 17.14.0 It still with .NET8
