### ISSUE TITLE
[CV2][CollectionView] Changing CollectionView's ItemsSource in runtime removes elements' parent seemingly random

### ISSUE THREAD

**Issue by Vetle444** [dotnet/maui#29491]
### Description

The elements in a CollectionView that uses CollectionViewHandler2 will get its parent removed if the ItemsSource changes. Thus, Source bindings is not usable anymore.

![Image](https://github.com/user-attachments/assets/c53750eb-c587-4e1d-b573-3a2d89b6d16c)

### Steps to Reproduce

1. Clone https://github.com/Vetle444/MauiTestApp/tree/collectionView2ParentBug/MauiTestApp
2. Make sure you are on branch: collectionView2ParentBug
3. Run app
4. Click `Bug` button
5. Click the `Reverse` button, observe that the Parent of some elements will get nullified.

### Link to public reproduction project repository

https://github.com/Vetle444/MauiTestApp/tree/collectionView2ParentBug/MauiTestApp

### Version with bug

9.0.70 SR7

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Relevant log output

```shell

```

**Comment by TamilarasanSF4853** [comment]
This issue has been verified in Visual Studio Code (1.100.1) with MAUI versions (9.0.0 & 9.0.70). It can be reproduced on iOS(CV2) platform. 
Note: Issue does not reproduced on CV1

**Comment by usman-karatela** [comment]
I have similar issue, I am changing ItemSource based on the DataTrigger, and once the ItemSource is changed the RelativeSource binding does not work, which is set to viewmodel. 

@Vetle444 do you know how can I apply your workaround in my case?


```
<DataTemplate>
				<StackLayout>
					<controls:CustomView />
					<StackLayout.GestureRecognizers>
						<TapGestureRecognizer
							Command="{Binding Source={RelativeSource AncestorType={x:Type viewModel:ContactsViewModel}}, Path=NavigateToContactDetailCommand}"
							CommandParameter="{Binding .}" />
					</StackLayout.GestureRecognizers>
				</StackLayout>
</DataTemplate>
```

the issue is only with CollectionViewHandler2 in iOS, it works fine with old Handler.

**Comment by usman-karatela** [comment]
@jfversluis is this issue fixed in [9.0.110 SR11](https://github.com/dotnet/maui/releases/tag/9.0.110)?

**Comment by jfversluis** [comment]
@usman-karatela it should be yes, please let us know!

**Comment by baaaaif** [comment]
@jfversluis i don't think so

SR11 is based on August 25 candidate. Unfortunately, many of the fixes I was hoping for are still missing in SR11, as they are only included in the September candidate.
https://github.com/dotnet/maui/blob/release/9.0.1xx-sr11/src/Controls/src/Core/Handlers/Items2/iOS/TemplatedCell2.cs is missing the changes from https://github.com/dotnet/maui/pull/29551/files

**Comment by jfversluis** [comment]
Sorry, seems I was too optimistic, these will be part of SR12 then!
