### ISSUE TITLE
MAUI App Icon Not Showing in IOS and Broken Icon in Android

### ISSUE THREAD

**Issue by renesh-lims** [dotnet/maui#29518]
### Description

I have created a MAUI application for iOS and Android. The application is working successfully, but the app icon is not displaying correctly. Instead, the default .NET app icon is shown, and on Android, it appears inaccurately.

I want to upload the app to the Play Store and App Store. I need urgent help.

### Steps to Reproduce

**_Project Settings_**

	<ItemGroup>
		
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" ForegroundScale="0.95" Color="#ffffff" />
		
		
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#003366" BaseSize="512,512" />

		
		<MauiImage Include="Resources\Images\*" />

		
		<MauiFont Include="Resources\Fonts\*" />

		
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <AndroidResource Remove="Platforms\Android\Resources\mipmap-anydpi-v26\ic_launcher.xml" />
	</ItemGroup>

**_Android Manifest_**

```
<application
		android:icon="@mipmap/appicon" 
		android:roundIcon="@mipmap/appicon_round"
		android:label="LQMS"
		android:supportsRtl="false"
		android:networkSecurityConfig="@xml/network_security_config"
		tools:replace="android:label,android:supportsRtl,android:icon,android:roundIcon" ></application>
```
**_PList_**

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>UIDeviceFamily</key>
	<array>
		<integer>1</integer>
		<integer>2</integer>
	</array>
	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>arm64</string>
	</array>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	
	<key>XSAppIconAssets</key>
	<string>Assets.xcassets/appicon.appiconset</string>
	<key>CFBundleIconName</key>
	<string>AppIcon</string>
	<key>CFBundleIdentifier</key>
	<string>com.sample.erp</string>
	<key>UIRequiresFullScreen</key>
	<true/>
	<key>UIStatusBarStyle</key>
	<string>UIStatusBarStyleLightContent</string>
	<key>UIBackgroundModes</key>
	<array>
		<string>audio</string>
		<string>location</string>
		<string>external-accessory</string>
		<string>bluetooth-central</string>
		<string>fetch</string>
		<string>remote-notification</string>
	</array>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSExceptionDomains</key>
		<dict>
			<key>lims.ae</key>
			<dict>
				<key>NSIncludesSubdomains</key>
				<true/>
				<key>NSExceptionMinimumTLSVersion</key>
				<string>TLSv1.0</string>
				<key>NSExceptionRequiresForwardSecrecy</key>
				<false/>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
				<key>NSAllowsArbitraryLoadsInWebContent</key>
				<true/>
				<key>NSRequiresCertificateTransparency</key>
				<string>No</string>
				<key>NSThirdPartyExceptionMinimumTLSVersion</key>
				<string>TLSv1.0</string>
				<key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
				<false/>
				<key>NSThirdPartyExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>
	</dict>
	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>You are about to use location!</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>This app needs access to your location to provide location-based features.</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>This app needs location access even in background for accurate service.</string>

	<key>NSCameraUsageDescription</key>
	<string>This app needs access to the camera to take photos.</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>This app needs access to photos.</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>This app needs access to microphone.</string>
	<key>NSPhotoLibraryAddUsageDescription</key>
	<string>This app needs access to the photo gallery.</string>
	<key>Custom Property</key>
	<string>The [app name] wants to use your microphone to record audio.</string>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>lyft</string>
		<string>fb</string>
	</array>
	<key>FirebaseAppDelegateProxyEnabled</key>
	<false/>
	<key>UIUserInterfaceStyle</key>
	<string>Light</string>
	<key>NSCalendarsUsageDescription</key>
	<string>This app uses calendars to create events and alerts.</string>
	<key>ITSAppUsesNonExemptEncryption</key>
	<false/>
	<key>UIFileSharingEnabled</key>
	<true/>
	<key>LSSupportsOpeningDocumentsInPlace</key>
	<true/>
	<key>NSAppleMusicUsageDescription</key>
	<string>This app may requires access to Media Library to play voice notes.</string>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<true/>
	<key>UISupportedExternalAccessoryProtocols</key>
	<array>
		<string>com.bixolon.protocol</string>
	</array>
	<key>NSBluetoothAlwaysUsageDescription</key>
	<string>Communication with the printer for printing.</string>
	<key>NSBluetoothPeripheralUsageDescription</key>
	<string>Communication with the printer for printing.</string>
	<key>CFBundleShortVersionString</key>
	<string>1</string>
	
</dict>
</plist>

```

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI, Yes, this used to work in Xamarin.Forms

### Affected platforms

iOS, Android

### Did you find any workaround?

**_Android Home Screen_**

<img width="273" alt="Image" src="https://github.com/user-attachments/assets/f8c7b878-06c4-40e4-97dd-50d98910537b" />

**_IOS - Build_** 

![Image](https://github.com/user-attachments/assets/2c3d3979-229b-4a16-98c7-5a199e601173)

IPAD- Home Screen

![Image](https://github.com/user-attachments/assets/927ebd65-7399-4317-a1dc-8a38b782eef9)

**_App Icons_**

![Image](https://github.com/user-attachments/assets/e9220df6-c605-452c-903f-9a4c6b4dfb2c)
![Image](https://github.com/user-attachments/assets/388f8509-53c1-44a9-9d4b-f0354961d365)

### Relevant log output

```shell

```

**Comment by ukehartmann** [comment]
@renesh-lims did you push it to the AppStore and tried a TestFlight build? That should show up with the correct logo. Also BaseSize="256,256" should fix the scaling issue.

**Comment by bhavanesh2001** [comment]
```xml
<key>XSAppIconAssets</key>
	<string>Assets.xcassets/appicon.appiconset</string>
	<key>CFBundleIconName</key>
	<string>AppIcon</string>
```

You shouldn't define `CFBundleIconName` in your Info.plist because, by default, it already includes `XSAppIconAssets`, and .NET MAUI will generate an asset catalog icon set automatically.

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/images/app-icons?view=net-maui-9.0&tabs=macios

**Comment by renesh-lims** [comment]
Hi Team,

The issue still persists on Android, and it's not working on iOS. 

I'm using a Windows PC with iTunes to debug the application.

**Comment by bhavanesh2001** [comment]
> <key>XSAppIconAssets</key>
> 	<string>Assets.xcassets/appicon.appiconset</string>
> 	<key>CFBundleIconName</key>
> 	<string>AppIcon</string>
> You shouldn't define `CFBundleIconName` in your Info.plist because, by default, it already includes `XSAppIconAssets`, and .NET MAUI will generate an asset catalog icon set automatically.
> 
> https://learn.microsoft.com/en-us/dotnet/maui/user-interface/images/app-icons?view=net-maui-9.0&tabs=macios
> 
> After removing CFBundleIconName, clean the solution, rebuild the app, uninstall existing app , redeploy app and then check if the issue is resolved.

@renesh-lims have you tried after making these changes?

**Comment by renesh-lims** [comment]
> > XSAppIconAssets
> > Assets.xcassets/appicon.appiconset
> > CFBundleIconName
> > AppIcon
> > You shouldn't define `CFBundleIconName` in your Info.plist because, by default, it already includes `XSAppIconAssets`, and .NET MAUI will generate an asset catalog icon set automatically.
> > https://learn.microsoft.com/en-us/dotnet/maui/user-interface/images/app-icons?view=net-maui-9.0&tabs=macios
> > After removing CFBundleIconName, clean the solution, rebuild the app, uninstall existing app , redeploy app and then check if the issue is resolved.
> 
> [@renesh-lims](https://github.com/renesh-lims) have you tried after making these changes?

Yes, tried that,

**Comment by bhavanesh2001** [comment]
If you still have issues, Please provide a reproduction project in which the issue can be reproduced.

**Comment by renesh-lims** [comment]
Unable to add package Plugin.Firebase.CloudMessaging 3.0.0


Restoring packages for R:\MAUI\ERP\LQMS.csproj...
  GET https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.cloudmessaging/index.json
  GET https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.core/index.json
  OK https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.core/index.json 418ms
  GET https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.core/10.24.0.1/adame.firebase.ios.core.10.24.0.1.nupkg
  OK https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.core/10.24.0.1/adame.firebase.ios.core.10.24.0.1.nupkg 26ms
  OK https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.cloudmessaging/index.json 491ms
  GET https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.cloudmessaging/10.24.0/adame.firebase.ios.cloudmessaging.10.24.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.cloudmessaging/10.24.0/adame.firebase.ios.cloudmessaging.10.24.0.nupkg 26ms
  GET https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.core/10.24.0/adame.firebase.ios.core.10.24.0.nupkg
  GET https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.installations/index.json
  OK https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.core/10.24.0/adame.firebase.ios.core.10.24.0.nupkg 51ms
  OK https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.installations/index.json 574ms
  GET https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.installations/10.24.0/adame.firebase.ios.installations.10.24.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.installations/10.24.0/adame.firebase.ios.installations.10.24.0.nupkg 85ms
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at NuGet.Packaging.PackageFileExtractor.ExtractPackageFile(String source, String target, Stream stream)
   at NuGet.Packaging.PackageArchiveReader.CopyFiles(String destination, IEnumerable`1 packageFiles, ExtractPackageFileDelegate extractFile, ILogger logger, CancellationToken token)
   at NuGet.Packaging.PackageReaderBase.CopyFilesAsync(String destination, IEnumerable`1 packageFiles, ExtractPackageFileDelegate extractFile, ILogger logger, CancellationToken cancellationToken)
   at NuGet.Packaging.PackageExtractor.<>c__DisplayClass5_0.<<InstallFromSourceAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Packaging.PackageExtractor.<InstallFromSourceAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.ProjectRestoreCommand.<InstallPackageAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Commands.ProjectRestoreCommand.<>c__DisplayClass15_1.<<InstallPackagesAsync>b__4>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.ProjectRestoreCommand.<InstallPackagesAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Commands.DependencyGraphResolver.<ResolveAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreCommand.<ExecuteRestoreAsync>d__120.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreCommand.<GenerateRestoreGraphsAsync>d__100.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreCommand.<ExecuteAsync>d__95.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreRunner.<ExecuteAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.RestoreRunner.<CompleteTaskAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Commands.RestoreRunner.<RunWithoutCommit>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.DependencyGraphRestoreUtility.<PreviewRestoreProjectsAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<PreviewBuildIntegratedProjectsActionsAsync>d__89.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<PreviewProjectsInstallPackageAsync>d__75.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.NuGetProjectManagerService.<>c__DisplayClass22_0.<<GetInstallActionsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.NuGetProjectManagerService.<CatchAndRethrowExceptionAsync>d__33`1.MoveNext()
Time Elapsed: 00:00:03.6223793
========== Finished ==========

**Comment by renesh-lims** [comment]
Which method did you use to deploy the application? Visual Studio with iTunes or Visual Studio with Pair to Mac?

I am using Visual Studio with iTunes on a Windows machine.

**Comment by bhavanesh2001** [comment]
> Which method did you use to deploy the application? Visual Studio with iTunes or Visual Studio with Pair to Mac?
> 
> I am using Visual Studio with iTunes on a Windows machine.

I deployed that with VS Code for mac on MacBook

**Comment by jaimeatsherpa** [comment]
> Which method did you use to deploy the application? Visual Studio with iTunes or Visual Studio with Pair to Mac?
> 
> I am using Visual Studio with iTunes on a Windows machine.

I you are using hot restart in Windows to pair an iOS device it wont show the icon as stated here in the limitations: [Deploy an iOS app using hot restart](https://learn.microsoft.com/en-us/dotnet/maui/ios/hot-restart?view=net-maui-9.0#limitations).

Leaving this here as it also took me a while to read it

**Comment by renesh-lims** [comment]
@jaimeatsherpa @bhavanesh2001 Thanks for your information
