### ISSUE TITLE
I1_Vertical_list_for_Multiple_Rows - Rotating the emulator would cause clipping on the description text.

### ISSUE THREAD

**Issue by Marnie-Majait** [dotnet/maui#29542]
### Description

Rotating the android emulator would cause clipping on the description text.

**Affected case:**
I1 - Vertical List for Multiple Rows

### Steps to Reproduce

1. Deploy https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests on android platform.
2. Click I1 -> Vertical List for Multiple Rows.
3. Rotate the android emulator to the right.
4. Observe that the description text is clipped inconsistently.

**Actual Behavior:**
The text description is clipped.

![Image](https://github.com/user-attachments/assets/66008126-cc4b-48f2-953b-58a5311d471d)

**Expected Behavior:**
The text description is not clipped.

![Image](https://github.com/user-attachments/assets/45fc158f-00a7-4a3b-a374-8ac0b05ca911)

### Link to public reproduction project repository

https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests

### Version with bug

Inflight/current - 9.0.80-ci.main.25265.24

### Is this a regression from previous behavior?

Yes, this used to work in 9.0.50 & 9.0.30. This can also be reproduced in 9.0.70 & 9.0.60.

### Affected platforms

Android

**Comment by PureWeen** [comment]
This should be fixed on SR9 by the following [PR](https://github.com/dotnet/maui/pull/30023)

We might get this out as service release to SR8 depending on timing of some other work. 

If you have a chance to validate the nugets from https://github.com/dotnet/maui/pull/30023 or the latest nugets from the "inflight" branch that would be helpful to make sure we actually fix you this time

**Comment by Zhanglirong-Winnie** [comment]
This issue still repro on SDK .NET10 Preview6, so I reopened this bug.

**Comment by PureWeen** [comment]
@Zhanglirong-Winnie have you confirmed this is no longer broken on the latest inflight branches?

**Comment by Zhanglirong-Winnie** [comment]
Hi, @PureWeen 
Yes, I'm sure this problem doesn't repro on the latest inflight version (9.0.90-ci.inflight.25330.3).

**Comment by PureWeen** [comment]
@Zhanglirong-Winnie is this still reproducing on preview7 of net10.0?

**Comment by Zhanglirong-Winnie** [comment]
Hi, @PureWeen 
This issue not repro on Maui version 10.0.0-preview.7.25379.3

**Comment by PureWeen** [comment]
@Zhanglirong-Winnie I'm closing this one 

If this should still be open please just create a new issue
