### ISSUE TITLE
[Mac Catalyst][Windows] TitleBar not reacting on UserAppTheme changes

### ISSUE THREAD

**Issue by bartlomiejsawarski** [dotnet/maui#30518]
### Description

I'm using TitleBar without setting BackgroundColor (I would like to stay with system default colours). When I change theme using system settings TitleBar correctly responds to this changes. But when I change [UserAppTheme](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.application.userapptheme?view=net-maui-9.0) TitleBar colour won't be updated (even after app restart)

https://github.com/user-attachments/assets/c14532e7-e9ac-4797-b60d-e39ef36c74d4

https://github.com/user-attachments/assets/a9a5be64-a674-41e2-b2d5-d77572dff034

### Steps to Reproduce

1. Create empty MAUI solution
2. Add buttons which on click would set for example `Application.Current.UserAppTheme = AppTheme.Dark;`
3. In `App.xaml.cs` change `CreateWindow` to:

```
    protected override Window CreateWindow(IActivationState? activationState)
    {
        var window = new Window(new AppShell());
        
        window.TitleBar = new TitleBar
        {
            Title = "MauiApp1",
            Subtitle = "Welcome to .NET MAUI",
            ForegroundColor = Colors.White,
            HeightRequest = 32
        };
        
        return window;
    }
```

**I'm using Microsoft.Maui.Controls 9.0.81**

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS, Windows

### Relevant log output

```shell

```

**Comment by kubaflo** [comment]
Hi @bartlomiejsawarski I have a fix for Catalyst here: https://github.com/dotnet/maui/pull/30525 :)

**Comment by sheiksyedm** [comment]
Similar issue: https://github.com/dotnet/maui/issues/30807

**Comment by jsuarezruiz** [comment]
The issue have been fixed by https://github.com/dotnet/maui/pull/30525

**Comment by karthikraja-arumugam** [comment]
@jsuarezruiz, The fix included only to MacCatalyst, the issue still persists on Windows.
