### ISSUE TITLE
Placeholder text alignment is wrong on windows

### ISSUE THREAD

**Issue by NogginBox** [dotnet/maui#3808]
### Description

The placeholder text for an Entry control is aligned wrong when viewed as Windows App:

![Placeholder-text-size](https://user-images.githubusercontent.com/729381/146655775-d4c5376e-7a64-40d5-87b4-826c57217249.png)
.
At first I thought it was too small. It was only when I saw them side by side in the above screenshot that I realised the alignment was wrong, but the text was the same size.

### Steps to Reproduce

The following XAML makes this. It was working fine in preview 10, and this wrong alignment only happened when I upgraded to preview 11.

The Entry is a grid row 70 high and the XAML for the Entry is:

```
<Entry
    Text="{Binding UriToScan, Mode=TwoWay}"
    Margin="20,20,5,0"
    Placeholder="placeholder text too small"
    IsEnabled="{Binding Scan.IsEntryAllowed}"
    IsSpellCheckEnabled="False"
    FontSize="18"
    HorizontalOptions="Fill" />
```

### Version with bug

Preview 11

### Last version that worked well

Preview 10 (current)

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041

### Did you find any workaround?

No

**Comment by wenwen60** [comment]
Reproduce on windows, attach repro sample
[Uploading MauiApp15.zip…]()

**Comment by Redth** [comment]
This is fixed in a newer release (either Preview 14 or the upcoming RC1).   I validated the sample above now produces expected results against our main branch:

![image](https://user-images.githubusercontent.com/271950/160130837-af3d2fe7-8761-4bfc-821f-7bfc361b40f3.png)

![image](https://user-images.githubusercontent.com/271950/160130899-6074e01a-8421-4df8-b41d-f62bf93a0bed.png)

**Comment by NogginBox** [comment]
Excellent. I can still see it in preview 14, so sounds like it must be a RC1 thing. Looking forward to it!!
