### ISSUE TITLE
Labels with HTML ignore text styling on IOS but not Android

### ISSUE THREAD

**Issue by owaits** [dotnet/maui#4230]
### Description

When setting the TextType in a Label to Html any styling of the label such as Font, FontSize and Color are ignored when rendered on IOS but not on Android.

So the following label when displayed on Android shows in Red with the correct Font and size but in IOS the text is shown in black with incorrect font and size.

` <Label Text="Hello, World!" TextType="Html" TextColor="Red"/>`

It is possible to work around this by using the WebView but then  it is not possible to get the background to appear consistent beneath the text when using multiple HTML fragments. 

### Steps to Reproduce

Create a Default Maui Application
Add  TextType="Html"  to one of the existing labels or add the code bellow.

` <Label Text="Hello, World!" TextType="Html" TextColor="Red"/>`

Run this on an IOS device and observe the text is black. Run the same app on Android and it has the correct colour.

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iPadIOS 15

### Did you find any workaround?

Using WebView with a css file is a poor work around and does not look good due to backgrounds not matching.  I could not find a way to make WebView show with a transparent background.

**Comment by mattscheffer** [comment]
Bug repros in 17.2.0 Preview 1. Using iPad emulator iOS 15.2. As you can see below, changing type to HTML lowered the font size and left the text black. Attempting on Android has text change to red as expected with a similar font size.

Repro project can be found at https://microsoft.sharepoint.com/:u:/r/teams/Mauitriage/Shared%20Documents/General/ReproProjects/4230.zip?csf=1&web=1&e=bH4t77

![image](https://user-images.githubusercontent.com/10537189/154376325-68a9b22e-be1e-4885-ac8c-7c1bc1193e7d.png)

**Comment by samhouts** [comment]
Still happens on 6.0.300-rc3.5543

**Comment by vhugogarcia** [comment]
@owaits I still believe it is by design. Because let's say you set a label with HTML type and then you set the text color to Orange using the "TextColor" property, but then your returned html string has red color on it.
`<strong style=\"color:red\">This is HTML text</strong>`

**Which color should the MAUI use and why?** 
These kind of decisions complicate things when they can be easy. If the Label is set to HTML type then it is what exactly is proposed to do, not trying to figure out how to assign properties to a type of label that is not supposed to do.

Probably, what could happen is that .NET MAUI in the future separate the labels into 2 segments:
* Plain/Formatted Labels
`<Label></Label>`
* HTML Labels
`<HtmlLabel></HtmlLabel>`

This separation could help to clarify the purpose of the element in the screen. :)

**Comment by owaits** [comment]
@vhugogarcia I see it more like the parameters are setting the body style on a web page but if the page contains more specific styling then that takes president. So the TextColor attribute is setting the body style for you but then the html can contain more specific styles. So in your example yes, it is correct that it is red. 

One advantage with having the parameters set the global style is that you can re-use the styles you have in your app which makes it really easy to incorporate HTML content that takes advantage of your app styles.

I am not sure how you would achieve dark and light app themes in your example without some complicated HTML parsing. You need to take into account that you may not be the author of the HTML, for example in GitHub I can enter this message with HTML and it gets re-formatted with the style and colour for GitHub.

I do agree with separating the Label control in Label and HTMLLabel though :-)

**Comment by hartez** [comment]
> @owaits I still believe it is by design. Because let's say you set a label with HTML type and then you set the text color to Orange using the "TextColor" property, but then your returned html string has red color on it. `<strong style=\"color:red\">This is HTML text\</strong\>`
> 
> **Which color should the MAUI use and why?** These kind of decisions complicate things when they can be easy. If the Label is set to HTML type then it is what exactly is proposed to do, not trying to figure out how to assign properties to a type of label that is not supposed to do.
> 
> Probably, what could happen is that .NET MAUI in the future separate the labels into 2 segments:
> 
> * Plain/Formatted Labels
>   `<Label></Label>`
> * HTML Labels
>   `<HtmlLabel></HtmlLabel>`
> 
> This separation could help to clarify the purpose of the element in the screen. :)

That's certainly the intention: https://github.com/dotnet/maui/issues/1082. I wish we'd had time to do this for .NET 7, but it'll be a .NET 8 thing at the earliest.

**Comment by hartez** [comment]
This is not intentional, and is definitely a bug - setting the text color for an HTML Label on iOS worked in Forms, so for consistency/migration purposes, it should be working in MAUI as well. (Even if it doesn't really make a lot of sense, as @vhugogarcia points out.)

**Comment by HobDev** [comment]
This is still an issue in .NET 7. Isn't the pull request associated with this bug  released.

**Comment by HobDev** [comment]
@hartez I am facing the issue on iOS and unable to style the html label with fontsize, textcolor etc. The above pull request is merged but still not been released. Should I open a new issue or wait.
