### ISSUE TITLE
Cursor jumps on Entry with IsPassword

### ISSUE THREAD

**Issue by christophbrunner** [dotnet/maui#5401]
### Description

When entering a password, the cursor jumps to the beginning of the field each time a key is entered.
![Maui-IsPassword](https://user-images.githubusercontent.com/1324374/158902783-78c88c19-5ed3-4736-bbc4-0c887921b2eb.gif)

### Steps to Reproduce

1. Create new project
2. Add a Entry with IsPassword-Attribute
`<Entry IsPassword="True" />`
4. Entering a password with the keyboard

### Version with bug

Preview 14 (current)

### Last version that worked well

Preview 13

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 21H2 (OSBuil 22000.556)

### Did you find any workaround?

No

**Comment by Amir-Care** [comment]
Verified not repro with Version 17.2.0 Preview 2.0 [32208.484.main]

   ![5401_windows](https://user-images.githubusercontent.com/99456025/158918646-ca150e78-b78e-44c2-8ac8-f53c2b284cd0.gif)

**Comment by egvijayanand** [comment]
Same issue. The cursor jumps to the start after the entry of each character.

**Comment by egvijayanand** [comment]
Simulation video attached.

https://user-images.githubusercontent.com/81947404/158982638-30e898f8-344d-43ac-a0dd-a80f62ad65a7.mp4

**Comment by egvijayanand** [comment]
#5414 has nothing to do with this issue. Simulated in a single app instance, apart from that they've no connection.

**Comment by emceelovin** [comment]
I have this exact issue as well, but was searching before I posted a dup. Same behavior on preview 14 as well.

**Comment by rborosak** [comment]
Can confirm the problem on Windows. It work on android

**Comment by osnipezzini** [comment]
Confirmed issue on Preview 14 here too

**Comment by tess123456** [comment]
I am still having a cursor issue when using a simple Entry control and setting isPassword = True. No TextTransform or converters. Issue is when running in Windows. I am using the latest 17.2.0 Preview 6.0. 

Issue is the same as others have previously highlighted - https://github.com/dotnet/maui/issues/5401#issuecomment-1072257277

The above verified fix seems to have a great deal of code around text transformation, however the problem I am having (and others have commented on) seems to be a problem with isPassword and the setting of the cursor. I do not wish to add a load of code behind for isPassword to work correctly. Any ideas if this is on the cards to be fixed any time soon? Thanks

**Comment by SotoiGhost** [comment]
@tess123456 the odd cursor behavior when using `IsPassword` was also fixed with the merge of the above PR. Here's a testcase using an `Entry` control with no `TextTransform` or `Converter`. Hope this helps! 😊 Don't hesitate to ask if you have any doubt!

https://user-images.githubusercontent.com/5924210/167453451-7f9fc24e-8a03-48c7-971d-3d49e31f2002.mp4

**Comment by tess123456** [comment]
@SotoiGhost This is not fixed for me when running under Windows (see comment from @christophbrunner ref #6977 ).

I think this issue needs to be reopened and resolved in windows.

**Comment by christophbrunner** [comment]
Jep, it is not fixed in RC3.
Please reopen this Bug.

**Comment by Redth** [comment]
The PR fixing this was not merged in time for RC3, the fix will be in GA
