### ISSUE TITLE
In RC1, FontImageSource does not work on Image.Source

### ISSUE THREAD

**Issue by Mephisztoe** [dotnet/maui#5859]
### Description

I can use for instance FontAwesome to have MAUI render FontIcons on Labels.

For example:
```xaml
<Label
    x:Name="HouseLabel"
    FontFamily="FA-S"
    FontSize="20"
    HorizontalTextAlignment="Center"
    Text="{x:Static fontAwesome:FontAwesomeIcons.House}"
    VerticalOptions="FillAndExpand" />
```

However, when using the FontImageSource on an Image, the FontIcon is not shown.

For example:
```xaml
<Image x:Name="HouseImage" >
    <Image.Source>
        <FontImageSource
            FontFamily="FA-S"
            Glyph="{x:Static fontAwesome:FontAwesomeIcons.House}"
            Size="20"
            Color="White" />
    </Image.Source>
</Image>
```

### Steps to Reproduce

1. Create a .NET MAUI App
2. Add an IconFont such as FontAwesome to the Resources\Fonts folder
3. Register the Font with MauiAppBuilder
4. Add an Image to the Home View referencing any glyph from the IconFont via FontImageSource

### Version with bug

Release Candidate 1

### Last version that worked well

Preview 14 (current)

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android

### Did you find any workaround?

Using a Label instead works. However, with Preview 14 I was using Images so that I can make use of specific properties I need for effects and animations. This won't work with a Label.

### Repro

The following zip contains an RC1 based MAUI project to show the problem. 
Also notice that on the AboutView, I tried to use a FontImageSource on a ToolbarItem and it ignores its Color property (this may of may not be related to [this issue](https://github.com/xamarin/Xamarin.Forms/issues/10898)).

📁 [MauiIssueFontImageSource.zip](https://github.com/dotnet/maui/files/8427583/MauiIssueFontImageSource.zip)

**Comment by kristinx0211** [comment]
repro on Android 12 and the above project.

**Comment by Redth** [comment]
Duplicate of #4013

**Comment by Redth** [comment]
Yes, this is fixed in https://github.com/dotnet/maui/pull/5876 (the image isn't shown at all) :)

**Comment by HausBJB** [comment]
The problem is still there, just tested.

Icon green is shown

Icon red not

Version with bug
Release Candidate 2

Android Version API 31
