### ISSUE TITLE
No Icons in AppShell

### ISSUE THREAD

**Issue by xxjnaxx** [dotnet/maui#6294]
### Description

The Android Emulator can't show icons in a FlyoutItem.

### Steps to Reproduce

1. Create a File > New .NET MAUI App
2. Add a AppShell with some FlyoutItems like so:  
  <FlyoutItem Title="Geräte" >

        <FlyoutItem.Icon>
            <FontImageSource FontFamily="FS900" Glyph="{x:Static fontAwesome:FontAwesomeIcons.Mobile}" Color="{StaticResource PrimaryColor}" >
            </FontImageSource>
        </FlyoutItem.Icon>
        <ShellContent ContentTemplate="{DataTemplate local:DevicesPage}"
                      Route="geraete"  />
    </FlyoutItem>

3. Debug -> the place will be empty. 
4. Try with WindowsMachine -> it works

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Preview 14

### Affected platforms

Android

### Affected platform versions

Android 11.0

**Comment by Redth** [comment]
This should be fixed in RC1 - there was a bug where the color needed to be set or they wouldn't appear and there was also a bug with font icon image sources.

**Comment by xxjnaxx** [comment]
![iconnn2](https://user-images.githubusercontent.com/104063296/164408590-5358e386-b91f-4100-9573-7c53e09782e3.png)

This is while using RC1

**Comment by devonuto** [comment]
> This should be fixed in RC1 - there was a bug where the color needed to be set or they wouldn't appear and there was also a bug with font icon image sources.

This wasn't fixed. I'm using Font Icon Images and am setting the color, but no images shown in Android in the flyout menu. Using VS 17.2 Preview 6.
