### ISSUE TITLE
TextColor of RadioButton seems to be always black for Mac Catalyst, despite setting it in constructor with e.g. new RadioButton { TextColor = Color.FromRgb(255, 0, 0), ... }

### ISSUE THREAD

**Issue by martin-honnen** [dotnet/maui#6430]
### Description

I have converted a small radio button sample from the Xamarin Forms gallery to MAUI, using RC 1, it is at https://github.com/martin-honnen/MAUIRC1RadioButtonGalleryExample. When running the sample app on Mac OS (i.e. Mac Catalyst) the sample works fine as far as selection of the radio buttons is concerned, however, although the RadioButtons are created with a TextColor e.g. `new RadioButton { Content = "Red", TextColor = Color.FromRgb(255, 0, 0), GroupName = "colors" }`, all button text is black. On Windows, the text is rendered in the assigned TextColor, so I think this is a rendering problem on Mac Catalyst/Mac OS
![MAUIRC1RadioButtonNoColour](https://user-images.githubusercontent.com/8466401/164799005-2abcdec7-15b4-4bfb-a296-c3c408659fdf.png)
.

### Steps to Reproduce

1. Clone the repository https://github.com/martin-honnen/MAUIRC1RadioButtonGalleryExample.
2. Build and run on Mac Catalyst with e.g. `dotnet build -t:Run -f net6.0-maccatalyst`
3. Check screen rendering, all RadioButton text is rendered black although the buttons of the first group are created with a `TextColor` e.g. `new RadioButton { Content = "Red", TextColor = Color.FromRgb(255, 0, 0), GroupName = "colors" }` and on Windows this means the text/content (e.g. "Red") is rendered in that color.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS Monterey 12.3.1, Mac mini M1

### Did you find any workaround?

I have not found a workaround.

**Comment by martin-honnen** [comment]
I have now also run the sample with an iOS simulator and the same lack of rendering of the colors occurs there as well; tested with iPad Pro 12.9 inch iOS 15.4 simulator
<img width="807" alt="ipadprosimulatormauirc1radiobutton" src="https://user-images.githubusercontent.com/8466401/164803514-7f24aac2-4eeb-43fd-bdd9-571b9e67b756.png">
.

**Comment by kristinx0211** [comment]
verified repro on mac catalyst with the above project.

**Comment by tekmun** [comment]
This issue happens in iOS 15.4 too (both physical and emulator).

**Comment by dustin-wojciechowski** [comment]
Pulling down the latest from Main, looks like this issue is fixed:

MacOS:
<img width="448" alt="image" src="https://user-images.githubusercontent.com/89540402/225160820-b784c85f-b2f5-477b-8c86-f3afa02ae266.png">
iOS:
<img width="366" alt="image" src="https://user-images.githubusercontent.com/89540402/225161056-6d42ec95-5c2b-40bd-be58-9aa395da993e.png">

**Comment by imsam67** [comment]
I'm still experiencing this issue. On Windows 11 using Visual Studio 17.5.2. The app is targeting .NET 7 and I have .NET 7.0.202 installed on my machine. No matter what color I set the `TextColor` to, the text remains invisible.

**Comment by dustin-wojciechowski** [comment]
@imsam67 I'm sorry to hear that. Would you mind creating a new issue with a reproduction and more information, like your target platform?
