### ISSUE TITLE
SwipeGestureRecognizer is not working

### ISSUE THREAD

**Issue by Symbai** [dotnet/maui#7403]
### Description

`SwipeGestureRecognizer` is not working on Android, the `Swiped` event is never raised. I only found this issue #14 which says its in Pending state but the issue hasn't been updated since 2 years. The [documentation for MAUI](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/gestures/swipe) sounds like it's implemented.

Is this a bug or is it really not implemented yet?

### Steps to Reproduce

```XAML
<Button>
          <Button.GestureRecognizers>
                    <SwipeGestureRecognizer Direction="Right" Swiped="SwipeGestureRecognizer_Swiped"/>
          </Button.GestureRecognizers>
</Button>
```

`SwipeGestureRecognizer_Swiped` event is never raised when I swipe in Android Simulator.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12, API 31, Android Simulator

**Comment by jfversluis** [comment]
Does it work if you use it on another element? Preferably one that does not have its own response to input? A Label maybe?

**Comment by Symbai** [comment]
Thanks for asking. It also does NOT work on a Label:

https://user-images.githubusercontent.com/14368203/169767229-cff1d53a-3515-4afd-aba7-bf925786010f.mp4

**Comment by VincentBu** [comment]
not repro with vs main build(32523.339.main).

**Comment by Symbai** [comment]
Can you repro this with RC3? I am not able to test main build but with RC3 so question is if its just RC3 vs main or if its just you aren't able to reproduce at all.

**Comment by VincentBu** [comment]
Here is my project, would you like to verify it on Android emulator? Just swipe the button and the counter is expected to increase.
[MauiApp7403.zip](https://github.com/dotnet/maui/files/8761100/MauiApp7403.zip)

**Comment by jsuarezruiz** [comment]
It is definitely implemented (GestureManager class). Testing on the current amin branch seems to work fine.
![fix-7403](https://user-images.githubusercontent.com/6755973/170060787-32fed9d0-2c2e-49d2-96d4-f1fa890de8ad.gif)

Could you try with GA?

**Comment by Symbai** [comment]
I dont know how to try the main branch. Is there an installer? I'm not good at cloning and building and running such large projects. Like I said I'm using RC3 via VS installer. I believe its easier for you to run it on that, then having me trying to get the main branch working.

**Comment by Symbai** [comment]
@jsuarezruiz I've now downloaded the MAIN branch following [this guide](https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md). And it still does not work. No idea why it does for you, are you using the same Android version and device?

**Comment by VladislavAntonyuk** [comment]
I confirm it works on GA with Label, but doesn't work on custom controls

**Comment by Symbai** [comment]
What are "custom controls"? I've tested this on a Button and a Listview and on both it fails.

**Comment by PureWeen** [comment]
@VincentBu can you test gain please?

**Comment by VincentBu** [comment]
verified with vs main build 32630.352, `SwipeGestureRecognizer` works fine.

**Comment by Symbai** [comment]
No idea what I am doing wrong then. Does not work in Android Emulator and on physical devices. I had 12 people testing it on their physical devices and all confirmed SwipeGesture isn't working. Can this depend on what machine you are building / publishing the project?

**Comment by VladislavAntonyuk** [comment]
Verified on 6.0.400 and it doesn't work.
To check use this sample: https://github.com/VladislavAntonyuk/MauiSamples/blob/main/CardLayout/CardsLayout.cs#L86
Replace PanGestureRecognizer with SwipeGestureRecognizer. PanGestureRecognizer fires events but SwipeGestureRecognizer doesn't.

**Comment by Symbai** [comment]
I can confirm what @VladislavAntonyuk said. `PanGestureRecognizer` is also working for me (as soon as I click, hold and drag the mouse in the emulator, the event is raised), but `SwipeGestureRecognizer` does not. I click, hold and drag, nothing happens and the `Swiped` event is never raised.

These were the changes I made:
```
	public CardsLayout()
	{
		var panGesture = new SwipeGestureRecognizer();
		panGesture.Swiped += PanGesture_Swiped;
		GestureRecognizers.Add(panGesture);
	}

	private void PanGesture_Swiped(object? sender, SwipedEventArgs e)
	{
		throw new NotImplementedException(); // <-- never raised
	}
```

**Comment by VincentBu** [comment]
repro with [VladislavAntonyuk](https://github.com/VladislavAntonyuk)'s sample.

**Comment by codeanees** [comment]
I confirm this issue still exists in .NET MAUI 7. I added swipe gesture to a content view. In Android, the gesture never works!!

**Comment by mibuswolf** [comment]
> 

In the grid the error its the same , i think in all controls

**Comment by H-A-Hristov** [comment]
Today I tested Gesture Detector Handlers on Android, and custom control extending ContentView. Everything worked (Pan, Pinch, Tap) except Swipe. Maui 7.0. This is important feature, not only for custom controls.

**Comment by erp931117** [comment]
This still doesn't work, Swipe definitely doesn't work, Visual Studio 17.4.3, .Net 7

**Comment by ne0rrmatrix** [comment]
I am working on a sample app that  I Should have out later today. It will demonstrate how to use swipe in a maui app with mvvm, using community toolkit. I am writing it now. I have it working in an app. I just want to write it all out so people can see it working with all the various layouts, buttons, images, etc. I will have examples in sample app for everyone to look at. It works out the methods microsoft put up on help pages included features not implemented yet. Using mvvm and toolkit I have figured out how to make it work.

**Comment by jsuarezruiz** [comment]
> https://github.com/ne0rrmatrix/SwipeGesturesSample.git

The repro link seems not to be working, could you update it?

**Comment by VladislavAntonyuk** [comment]
@jsuarezruiz please try my sample:
https://github.com/VladislavAntonyuk/MauiSamples/blob/main/CardLayout/CardsLayout.cs#L86
Replace PanGestureRecognizer with SwipeGestureRecognizer. PanGestureRecognizer fires events but SwipeGestureRecognizer doesn't.
https://github.com/dotnet/maui/issues/7403#issuecomment-1172064417

**Comment by ne0rrmatrix** [comment]
> > https://github.com/ne0rrmatrix/SwipeGesturesSample.git
> 
> The repro link seems not to be working, could you update it?

Fixed link. https://github.com/ne0rrmatrix/MediaPlayerBugSwipeGestures

**Comment by AnnYang01** [comment]
Verified this on Visual Studio Enterprise 17.6.0 Preview 6.0. This issue does not repro on Android emulator (13.0-API 33) with below Project.
[MauiApp7.zip](https://github.com/dotnet/maui/files/11426582/MauiApp7.zip)

**Comment by VladislavAntonyuk** [comment]
@AnnYang01 please reopen it. the issue still reproduces https://github.com/VladislavAntonyuk/MauiSamples/blob/main/CardLayout
